In [1]:
#Data structures
#--meaning --how can we effectively store data ---> data structure
#Python
# mutable ---insert/update/delete
#   list,set,dictionary
# immutable ---cannot change once created
#  tuple

In [2]:
#List---> ordered
#         allow duplicates
#         indexed --0 indexed
#         working functions

In [3]:
l1 = list()
l1 =[]
print(l1,type(l1))

[] <class 'list'>

In [5]:
l1.append(22)
l1.append(33)
l1.append(44)
print(l1)

[22, 33, 44]

In [6]:
l1[0]

22

In [7]:
l1[1]

33

In [8]:
l1[2]

44

In [9]:
print(l1)

[22, 33, 44]

In [10]:
l1[1]=34
print(l1)

[22, 34, 44]

In [11]:
l1.remove(34)

In [12]:
print(l1)

[22, 44]

In [13]:
del l1[0]
print(l1)

[44]

In [14]:
l1=[10,20,30]

In [15]:
10 in l1

True

In [16]:
40 in l1

False

In [17]:
l1=[10,10,10,10]

In [18]:
l1.remove(10)

In [19]:
l1

[10, 10, 10]

In [20]:
while 10 in l1:
    l1.remove(10)
print(l1)

[]

In [21]:
l1=[10,20,30,40]

In [22]:
for element in l1:
    print(element)

10
20
30
40

In [23]:
for i,e in enumerate(l1):
    print(i,e)

0 10
1 20
2 30
3 40

In [24]:
l1=[10,20,30]
l2=[40,50]
l3 = l1+l2
print(l3)

[10, 20, 30, 40, 50]

In [25]:
l3.reverse()

None

In [26]:
l3

[50, 40, 30, 20, 10]

In [27]:
l4=["a","b",11,22]
l5=[11,22,33]
l6=l4+l5
print(l6)

['a', 'b', 11, 22, 11, 22, 33]

In [28]:
print(l3)
l3.clear()
print(l3)

[50, 40, 30, 20, 10]
[]

In [29]:
#Set is a data structure:
#does not allow duplicates
#not ordered

In [30]:
s1=set()

In [31]:
s1.add(22)
s1.add(23)
s1.add(22)
print(s1)

{22, 23}

In [32]:
s1 = {22,33,44,22}
print(s1)

{33, 44, 22}

In [33]:
for element in s1:
    print(element)

33
44
22

In [34]:
l1=[10,10,10,20]
s1 =set(l1)
print(s1)

{10, 20}

In [36]:
#Set theory
s1 = {10,20,30}
s2={10,20}
s3={40,50}

In [37]:
s1.intersection(s2)

{10, 20}

In [38]:
s1.intersection(s3)

set()

In [39]:
s1-s2

{30}

In [40]:
s1.issuperset(s2)

True

In [41]:
s2.issubset(s1)

True

In [42]:
s1.isdisjoint(s3)

True

In [43]:
s1.isdisjoint(s2)

False

In [44]:
#Dictionary
#Key value mapping
#us: dollars, in:inr....
#Key cannot be duplicated

In [45]:
d1 = {}
d1 = dict()

In [46]:
d1["US"]="United states"
d1["IN"]="India"
print(d1)

{'US': 'United states', 'IN': 'India'}

In [47]:
d1={'US': 'United states', 'IN': 'India'}
print(d1)

{'US': 'United states', 'IN': 'India'}

In [48]:
d1["US"]

'United states'

In [49]:
d1["IN"]

'India'

In [50]:
d1["CN"]

KeyError: 'CN'

In [51]:
d1.get("US")

'United states'

In [52]:
d1.get("IN")

'India'

In [55]:
print(d1.get("CN"))

None

In [56]:
d1["US"]="United states of America"
print(d1)

{'US': 'United states of America', 'IN': 'India'}

In [57]:
del d1["US"]

In [58]:
print(d1)

{'IN': 'India'}

In [59]:
d1={'US': 'United states of America', 'IN': 'India'}

In [60]:
for k,v in d1.items():
    print(k,v)

US United states of America
IN India

In [61]:
d1["CN"]="China"
print(d1)

{'US': 'United states of America', 'IN': 'India', 'CN': 'China'}

In [64]:
d1.update({"AF":"Afg","BH":"Bhutan"})

In [65]:
d1

{'US': 'United states of America',
 'IN': 'India',
 'CN': 'China',
 'AF': 'Afg',
 'BH': 'Bhutan'}

In [66]:
d1['US']

'United states of America'

In [67]:
"US" in d1

True

In [68]:
"BR" in d1

False

In [69]:
d1.keys()

dict_keys(['US', 'IN', 'CN', 'AF', 'BH'])

In [70]:
d1.values()

dict_values(['United states of America', 'India', 'China', 'Afg', 'Bhutan'])

In [71]:
d1.clear()

In [72]:
d1

{}

In [73]:
len(d1)

0

In [ ]:
#immutable
#tuple

In [74]:
t1=tuple()
t1=()

In [75]:
t1=(10,20,30)
print(t1)

(10, 20, 30)

In [76]:
t1[0]

10

In [77]:
t1[0]=99

TypeError: 'tuple' object does not support item assignment

In [78]:
for element in t1:
    print(element)

10
20
30

In [79]:
t1=(10,20)
t1=(20,30)

In [80]:
a,b=t1
print(a)
print(b)

20
30

In [81]:
from collections import Counter

In [82]:
word1="hello1"
word1_count=Counter(word1)
print(word1_count)

Counter({'l': 2, 'h': 1, 'e': 1, 'o': 1, '1': 1})

In [83]:
countries=["IN","IN","US","UK","UK"]
countries_count=Counter(countries)
print(countries_count)

Counter({'IN': 2, 'UK': 2, 'US': 1})

In [84]:
countries_count["IN"]

2

In [85]:
countries_count.most_common(2)

[('IN', 2), ('UK', 2)]

In [86]:
from collections import defaultdict

In [96]:
d1 = defaultdict(int)

In [97]:
d1

defaultdict(int, {})

In [98]:
d1["US"]

0

In [99]:
d1

defaultdict(int, {'US': 0})

In [100]:
d1["IN"] = +1
print(d1)

defaultdict(<class 'int'>, {'US': 0, 'IN': 1})

In [101]:
d1=defaultdict(str)

In [102]:
d1["UK"]

''

In [103]:
from collections import deque

In [104]:
m1=deque([11,22,33])

In [105]:
m1

deque([11, 22, 33])

In [106]:
m1.append(44)
print(m1)

deque([11, 22, 33, 44])

In [107]:
m1.appendleft(55)
print(m1)

deque([55, 11, 22, 33, 44])

In [108]:
m1.pop()
print(m1)

deque([55, 11, 22, 33])

In [109]:
m1.popleft()
print(m1)

deque([11, 22, 33])

In [110]:
from collections import OrderedDict

In [111]:
#Orderred dict 
od=OrderedDict()

In [112]:
od["IN"]="India"
od["US"]="United states"

In [113]:
print(od)

OrderedDict([('IN', 'India'), ('US', 'United states')])

In [114]:
def power(x,n):
    return x ** n

In [115]:
power(2,3)

8

In [116]:
power(n=3,x=2)

8

In [117]:
def add(*values):#* indicates variable arguments
    total = 0
    for v in values:
        total =total +v
    return total

In [118]:
add(22,33)

55

In [119]:
add(10,20,30)

60

In [122]:
def keyvalue(**args):#Kwargs key value arguments
    for k,v in args.items():
        print(k,v)

In [123]:
keyvalue(name="Vishwa",age=55)

name Vishwa
age 55

In [124]:
#Meta programming
#Within python --u can create functions within functions

In [125]:
def outer1():
    print("Within outer1")
    def inner1():
        print("Within inner1")
    inner1()

In [126]:
outer1()

Within outer1
Within inner1

In [127]:
#variables can store functions
#function can be returned

In [128]:
def outer2():
    print("Within outer2")
    def inner2():
        print("Within inner2")
    return inner2

In [129]:
f1=outer2()

Within outer2

In [130]:
f1()

Within inner2

In [131]:
f1()

Within inner2

In [132]:
f1

In [133]:
outer2()()

Within outer2
Within inner2

In [134]:
def outer3(n):
    print("Within outer3 n",n)
    def inner(x):
        print("x is",x,"n is",n)
        return x**n
    return inner

In [135]:
o1=outer3(4)

Within outer3 n 4

In [136]:
o1(2)

x is 2 n is 4

16

In [137]:
o1(3)

x is 3 n is 4

81

In [138]:
#In python function can be passed as argument to another function
def outer4(param1):
    print("Within outer 4")
    def inner():
        print("Before calling param1")
        param1()
        print("After calling param1")
    return inner

In [139]:
def hello():
    print("Hello from hello function")

In [140]:
f1=outer4(hello)

Within outer 4

In [141]:
f1()

Before calling param1
Hello from hello function
After calling param1

In [142]:
@outer4#Thi is equaivalent of f1=outer4(hello)
def hello1():
    print("From hello1 ")

Within outer 4

In [143]:
hello1()

Before calling param1
From hello1
After calling param1

In [145]:
@outer4
def welcome():
    print("Welcome")

Within outer 4

In [146]:
welcome()

Before calling param1
Welcome
After calling param1

In [147]:
# 4! =4 * 3 * 2 * 1

In [148]:
def factorial(n):
    if n == 1:
        return n
    else:
        return n*factorial(n-1)

In [149]:
res=factorial(4)

In [150]:
res

24

In [151]:
#Open file
#read/write
#close

In [152]:
op=open("C://training//data//1.txt","w")
op.write("Hello \n")
op.write("Welcome")
op.close()

In [153]:
ip = open("C://training//data//1.txt","r")
content=ip.read()#reads the entire content
ip.close()
print(content)

Hello
Welcome

In [155]:
ip = open("C://training//data//1.txt","r")
for line in ip:
    print(line.strip())
ip.close()

Hello
Welcome

In [156]:
with open("C://training//data//1.txt","r") as ip:#As soon as scope is over file is autoclosed
    for line in  ip:
        print(line)

Hello

Welcome

In [157]:
import csv

In [159]:
dataLst=[{"id":1,"name":"Vishwa"},{"id":2,"name":"Vishwa"}]

In [161]:
with open("C://training//data//sample.csv","a",newline='') as op:
    dw=csv.DictWriter(fieldnames=["id","name"],f=op)
    dw.writeheader()
    dw.writerows(dataLst)

In [162]:
with open("C://training//data//sample.csv","r") as op:
    dr=csv.DictReader(op)
    for data in dr:
        print(data)

{'id': '1', 'name': 'Vishwa'}
{'id': '2', 'name': 'Vishwa'}

In [163]:
import json

In [164]:
with open("C://training//data//sample.json","w") as op:
    json.dump(dataLst,op)

In [165]:
with open("C://training//data//sample.json","r") as ip:
    dataFromjson=json.load(ip)
    print(dataFromjson)

[{'id': 1, 'name': 'Vishwa'}, {'id': 2, 'name': 'Vishwa'}]

In [166]:
pip install lxml

Requirement already satisfied: lxml in c:\python311\lib\site-packages (5.4.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [167]:
#<name> <firstname></firstname><lastname></lastname></name>

In [168]:
from lxml import etree

In [171]:
name1=etree.Element("name")
fname1=etree.Element("firstName")
lname1=etree.Element("lastName")
fname1.text="Vishwa"
lname1.text="Vishwa"
name1.append(fname1)
name1.append(lname1)
xmlString=etree.tostring(name1,pretty_print=True).decode("utf-8")
print(xmlString)

<name>
  <firstName>Vishwa</firstName>
  <lastName>Vishwa</lastName>
</name>

In [172]:
with open("C://training//data//1.xml","w") as op:
    op.write(xmlString)

In [175]:
with open("C://training//data//1.xml","r") as ip:
    xml=etree.parse(ip)
    root=xml.getroot()
    print(root.find("firstName").text)
    print(root.find("lastName").text)

Vishwa
Vishwa

In [176]:
pip install requests

Requirement already satisfied: requests in c:\users\vishwa\appdata\roaming\python\python311\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from requests) (2024.12.14)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [178]:
import requests
jsondata=requests.get("https://jsonplaceholder.typicode.com/todos/")

In [180]:
jsondata.status_code

200

In [181]:
jsondata.text

'[\n  {\n    "userId": 1,\n    "id": 1,\n    "title": "delectus aut autem",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 2,\n    "title": "quis ut nam facilis et officia qui",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 3,\n    "title": "fugiat veniam minus",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 4,\n    "title": "et porro tempora",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 5,\n    "title": "laboriosam mollitia et enim quasi adipisci quia provident illum",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 6,\n    "title": "qui ullam ratione quibusdam voluptatem quia omnis",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 7,\n    "title": "illo expedita consequatur quia in",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 8,\n    "title": "quo adipisci enim quam ut ab",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 9,\n    "title": "molestiae perspiciatis ipsa",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 10,\n    "title": "illo est ratione doloremque quia maiores aut",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 11,\n    "title": "vero rerum temporibus dolor",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 12,\n    "title": "ipsa repellendus fugit nisi",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 13,\n    "title": "et doloremque nulla",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 14,\n    "title": "repellendus sunt dolores architecto voluptatum",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 15,\n    "title": "ab voluptatum amet voluptas",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 16,\n    "title": "accusamus eos facilis sint et aut voluptatem",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 17,\n    "title": "quo laboriosam deleniti aut qui",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 18,\n    "title": "dolorum est consequatur ea mollitia in culpa",\n    "completed": false\n  },\n  {\n    "userId": 1,\n    "id": 19,\n    "title": "molestiae ipsa aut voluptatibus pariatur dolor nihil",\n    "completed": true\n  },\n  {\n    "userId": 1,\n    "id": 20,\n    "title": "ullam nobis libero sapiente ad optio sint",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 21,\n    "title": "suscipit repellat esse quibusdam voluptatem incidunt",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 22,\n    "title": "distinctio vitae autem nihil ut molestias quo",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 23,\n    "title": "et itaque necessitatibus maxime molestiae qui quas velit",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 24,\n    "title": "adipisci non ad dicta qui amet quaerat doloribus ea",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 25,\n    "title": "voluptas quo tenetur perspiciatis explicabo natus",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 26,\n    "title": "aliquam aut quasi",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 27,\n    "title": "veritatis pariatur delectus",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 28,\n    "title": "nesciunt totam sit blanditiis sit",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 29,\n    "title": "laborum aut in quam",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 30,\n    "title": "nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 31,\n    "title": "repudiandae totam in est sint facere fuga",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 32,\n    "title": "earum doloribus ea doloremque quis",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 33,\n    "title": "sint sit aut vero",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 34,\n    "title": "porro aut necessitatibus eaque distinctio",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 35,\n    "title": "repellendus veritatis molestias dicta incidunt",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 36,\n    "title": "excepturi deleniti adipisci voluptatem et neque optio illum ad",\n    "completed": true\n  },\n  {\n    "userId": 2,\n    "id": 37,\n    "title": "sunt cum tempora",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 38,\n    "title": "totam quia non",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 39,\n    "title": "doloremque quibusdam asperiores libero corrupti illum qui omnis",\n    "completed": false\n  },\n  {\n    "userId": 2,\n    "id": 40,\n    "title": "totam atque quo nesciunt",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 41,\n    "title": "aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 42,\n    "title": "rerum perferendis error quia ut eveniet",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 43,\n    "title": "tempore ut sint quis recusandae",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 44,\n    "title": "cum debitis quis accusamus doloremque ipsa natus sapiente omnis",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 45,\n    "title": "velit soluta adipisci molestias reiciendis harum",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 46,\n    "title": "vel voluptatem repellat nihil placeat corporis",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 47,\n    "title": "nam qui rerum fugiat accusamus",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 48,\n    "title": "sit reprehenderit omnis quia",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 49,\n    "title": "ut necessitatibus aut maiores debitis officia blanditiis velit et",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 50,\n    "title": "cupiditate necessitatibus ullam aut quis dolor voluptate",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 51,\n    "title": "distinctio exercitationem ab doloribus",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 52,\n    "title": "nesciunt dolorum quis recusandae ad pariatur ratione",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 53,\n    "title": "qui labore est occaecati recusandae aliquid quam",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 54,\n    "title": "quis et est ut voluptate quam dolor",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 55,\n    "title": "voluptatum omnis minima qui occaecati provident nulla voluptatem ratione",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 56,\n    "title": "deleniti ea temporibus enim",\n    "completed": true\n  },\n  {\n    "userId": 3,\n    "id": 57,\n    "title": "pariatur et magnam ea doloribus similique voluptatem rerum quia",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 58,\n    "title": "est dicta totam qui explicabo doloribus qui dignissimos",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 59,\n    "title": "perspiciatis velit id laborum placeat iusto et aliquam odio",\n    "completed": false\n  },\n  {\n    "userId": 3,\n    "id": 60,\n    "title": "et sequi qui architecto ut adipisci",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 61,\n    "title": "odit optio omnis qui sunt",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 62,\n    "title": "et placeat et tempore aspernatur sint numquam",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 63,\n    "title": "doloremque aut dolores quidem fuga qui nulla",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 64,\n    "title": "voluptas consequatur qui ut quia magnam nemo esse",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 65,\n    "title": "fugiat pariatur ratione ut asperiores necessitatibus magni",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 66,\n    "title": "rerum eum molestias autem voluptatum sit optio",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 67,\n    "title": "quia voluptatibus voluptatem quos similique maiores repellat",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 68,\n    "title": "aut id perspiciatis voluptatem iusto",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 69,\n    "title": "doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 70,\n    "title": "ut sequi accusantium et mollitia delectus sunt",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 71,\n    "title": "aut velit saepe ullam",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 72,\n    "title": "praesentium facilis facere quis harum voluptatibus voluptatem eum",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 73,\n    "title": "sint amet quia totam corporis qui exercitationem commodi",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 74,\n    "title": "expedita tempore nobis eveniet laborum maiores",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 75,\n    "title": "occaecati adipisci est possimus totam",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 76,\n    "title": "sequi dolorem sed",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 77,\n    "title": "maiores aut nesciunt delectus exercitationem vel assumenda eligendi at",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 78,\n    "title": "reiciendis est magnam amet nemo iste recusandae impedit quaerat",\n    "completed": false\n  },\n  {\n    "userId": 4,\n    "id": 79,\n    "title": "eum ipsa maxime ut",\n    "completed": true\n  },\n  {\n    "userId": 4,\n    "id": 80,\n    "title": "tempore molestias dolores rerum sequi voluptates ipsum consequatur",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 81,\n    "title": "suscipit qui totam",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 82,\n    "title": "voluptates eum voluptas et dicta",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 83,\n    "title": "quidem at rerum quis ex aut sit quam",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 84,\n    "title": "sunt veritatis ut voluptate",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 85,\n    "title": "et quia ad iste a",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 86,\n    "title": "incidunt ut saepe autem",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 87,\n    "title": "laudantium quae eligendi consequatur quia et vero autem",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 88,\n    "title": "vitae aut excepturi laboriosam sint aliquam et et accusantium",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 89,\n    "title": "sequi ut omnis et",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 90,\n    "title": "molestiae nisi accusantium tenetur dolorem et",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 91,\n    "title": "nulla quis consequatur saepe qui id expedita",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 92,\n    "title": "in omnis laboriosam",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 93,\n    "title": "odio iure consequatur molestiae quibusdam necessitatibus quia sint",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 94,\n    "title": "facilis modi saepe mollitia",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 95,\n    "title": "vel nihil et molestiae iusto assumenda nemo quo ut",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 96,\n    "title": "nobis suscipit ducimus enim asperiores voluptas",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 97,\n    "title": "dolorum laboriosam eos qui iure aliquam",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 98,\n    "title": "debitis accusantium ut quo facilis nihil quis sapiente necessitatibus",\n    "completed": true\n  },\n  {\n    "userId": 5,\n    "id": 99,\n    "title": "neque voluptates ratione",\n    "completed": false\n  },\n  {\n    "userId": 5,\n    "id": 100,\n    "title": "excepturi a et neque qui expedita vel voluptate",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 101,\n    "title": "explicabo enim cumque porro aperiam occaecati minima",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 102,\n    "title": "sed ab consequatur",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 103,\n    "title": "non sunt delectus illo nulla tenetur enim omnis",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 104,\n    "title": "excepturi non laudantium quo",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 105,\n    "title": "totam quia dolorem et illum repellat voluptas optio",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 106,\n    "title": "ad illo quis voluptatem temporibus",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 107,\n    "title": "praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 108,\n    "title": "a eos eaque nihil et exercitationem incidunt delectus",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 109,\n    "title": "autem temporibus harum quisquam in culpa",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 110,\n    "title": "aut aut ea corporis",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 111,\n    "title": "magni accusantium labore et id quis provident",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 112,\n    "title": "consectetur impedit quisquam qui deserunt non rerum consequuntur eius",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 113,\n    "title": "quia atque aliquam sunt impedit voluptatum rerum assumenda nisi",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 114,\n    "title": "cupiditate quos possimus corporis quisquam exercitationem beatae",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 115,\n    "title": "sed et ea eum",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 116,\n    "title": "ipsa dolores vel facilis ut",\n    "completed": true\n  },\n  {\n    "userId": 6,\n    "id": 117,\n    "title": "sequi quae est et qui qui eveniet asperiores",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 118,\n    "title": "quia modi consequatur vero fugiat",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 119,\n    "title": "corporis ducimus ea perspiciatis iste",\n    "completed": false\n  },\n  {\n    "userId": 6,\n    "id": 120,\n    "title": "dolorem laboriosam vel voluptas et aliquam quasi",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 121,\n    "title": "inventore aut nihil minima laudantium hic qui omnis",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 122,\n    "title": "provident aut nobis culpa",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 123,\n    "title": "esse et quis iste est earum aut impedit",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 124,\n    "title": "qui consectetur id",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 125,\n    "title": "aut quasi autem iste tempore illum possimus",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 126,\n    "title": "ut asperiores perspiciatis veniam ipsum rerum saepe",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 127,\n    "title": "voluptatem libero consectetur rerum ut",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 128,\n    "title": "eius omnis est qui voluptatem autem",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 129,\n    "title": "rerum culpa quis harum",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 130,\n    "title": "nulla aliquid eveniet harum laborum libero alias ut unde",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 131,\n    "title": "qui ea incidunt quis",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 132,\n    "title": "qui molestiae voluptatibus velit iure harum quisquam",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 133,\n    "title": "et labore eos enim rerum consequatur sunt",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 134,\n    "title": "molestiae doloribus et laborum quod ea",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 135,\n    "title": "facere ipsa nam eum voluptates reiciendis vero qui",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 136,\n    "title": "asperiores illo tempora fuga sed ut quasi adipisci",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 137,\n    "title": "qui sit non",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 138,\n    "title": "placeat minima consequatur rem qui ut",\n    "completed": true\n  },\n  {\n    "userId": 7,\n    "id": 139,\n    "title": "consequatur doloribus id possimus voluptas a voluptatem",\n    "completed": false\n  },\n  {\n    "userId": 7,\n    "id": 140,\n    "title": "aut consectetur in blanditiis deserunt quia sed laboriosam",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 141,\n    "title": "explicabo consectetur debitis voluptates quas quae culpa rerum non",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 142,\n    "title": "maiores accusantium architecto necessitatibus reiciendis ea aut",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 143,\n    "title": "eum non recusandae cupiditate animi",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 144,\n    "title": "ut eum exercitationem sint",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 145,\n    "title": "beatae qui ullam incidunt voluptatem non nisi aliquam",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 146,\n    "title": "molestiae suscipit ratione nihil odio libero impedit vero totam",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 147,\n    "title": "eum itaque quod reprehenderit et facilis dolor autem ut",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 148,\n    "title": "esse quas et quo quasi exercitationem",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 149,\n    "title": "animi voluptas quod perferendis est",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 150,\n    "title": "eos amet tempore laudantium fugit a",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 151,\n    "title": "accusamus adipisci dicta qui quo ea explicabo sed vero",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 152,\n    "title": "odit eligendi recusandae doloremque cumque non",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 153,\n    "title": "ea aperiam consequatur qui repellat eos",\n    "completed": false\n  },\n  {\n    "userId": 8,\n    "id": 154,\n    "title": "rerum non ex sapiente",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 155,\n    "title": "voluptatem nobis consequatur et assumenda magnam",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 156,\n    "title": "nam quia quia nulla repellat assumenda quibusdam sit nobis",\n    "completed": true\n  },\n  {\n    "userId": 8,\n    "id": 157,\n    "title": "dolorem veniam quisquam deserunt repellendus

In [182]:
jsonlist=jsondata.json()

In [183]:
jsonlist

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False},
 {'userId': 1,
  'id': 2,
  'title': 'quis ut nam facilis et officia qui',
  'completed': False},
 {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False},
 {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True},
 {'userId': 1,
  'id': 5,
  'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum',
  'completed': False},
 {'userId': 1,
  'id': 6,
  'title': 'qui ullam ratione quibusdam voluptatem quia omnis',
  'completed': False},
 {'userId': 1,
  'id': 7,
  'title': 'illo expedita consequatur quia in',
  'completed': False},
 {'userId': 1,
  'id': 8,
  'title': 'quo adipisci enim quam ut ab',
  'completed': True},
 {'userId': 1,
  'id': 9,
  'title': 'molestiae perspiciatis ipsa',
  'completed': False},
 {'userId': 1,
  'id': 10,
  'title': 'illo est ratione doloremque quia maiores aut',
  'completed': True},
 {'userId': 1,
  'id': 11,
  'title': 'vero rerum temporibus dolor',
  'completed': True},
 {'userId': 1,
  'id': 12,
  'title': 'ipsa repellendus fugit nisi',
  'completed': True},
 {'userId': 1, 'id': 13, 'title': 'et doloremque nulla', 'completed': False},
 {'userId': 1,
  'id': 14,
  'title': 'repellendus sunt dolores architecto voluptatum',
  'completed': True},
 {'userId': 1,
  'id': 15,
  'title': 'ab voluptatum amet voluptas',
  'completed': True},
 {'userId': 1,
  'id': 16,
  'title': 'accusamus eos facilis sint et aut voluptatem',
  'completed': True},
 {'userId': 1,
  'id': 17,
  'title': 'quo laboriosam deleniti aut qui',
  'completed': True},
 {'userId': 1,
  'id': 18,
  'title': 'dolorum est consequatur ea mollitia in culpa',
  'completed': False},
 {'userId': 1,
  'id': 19,
  'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil',
  'completed': True},
 {'userId': 1,
  'id': 20,
  'title': 'ullam nobis libero sapiente ad optio sint',
  'completed': True},
 {'userId': 2,
  'id': 21,
  'title': 'suscipit repellat esse quibusdam voluptatem incidunt',
  'completed': False},
 {'userId': 2,
  'id': 22,
  'title': 'distinctio vitae autem nihil ut molestias quo',
  'completed': True},
 {'userId': 2,
  'id': 23,
  'title': 'et itaque necessitatibus maxime molestiae qui quas velit',
  'completed': False},
 {'userId': 2,
  'id': 24,
  'title': 'adipisci non ad dicta qui amet quaerat doloribus ea',
  'completed': False},
 {'userId': 2,
  'id': 25,
  'title': 'voluptas quo tenetur perspiciatis explicabo natus',
  'completed': True},
 {'userId': 2, 'id': 26, 'title': 'aliquam aut quasi', 'completed': True},
 {'userId': 2,
  'id': 27,
  'title': 'veritatis pariatur delectus',
  'completed': True},
 {'userId': 2,
  'id': 28,
  'title': 'nesciunt totam sit blanditiis sit',
  'completed': False},
 {'userId': 2, 'id': 29, 'title': 'laborum aut in quam', 'completed': False},
 {'userId': 2,
  'id': 30,
  'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis',
  'completed': True},
 {'userId': 2,
  'id': 31,
  'title': 'repudiandae totam in est sint facere fuga',
  'completed': False},
 {'userId': 2,
  'id': 32,
  'title': 'earum doloribus ea doloremque quis',
  'completed': False},
 {'userId': 2, 'id': 33, 'title': 'sint sit aut vero', 'completed': False},
 {'userId': 2,
  'id': 34,
  'title': 'porro aut necessitatibus eaque distinctio',
  'completed': False},
 {'userId': 2,
  'id': 35,
  'title': 'repellendus veritatis molestias dicta incidunt',
  'completed': True},
 {'userId': 2,
  'id': 36,
  'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad',
  'completed': True},
 {'userId': 2, 'id': 37, 'title': 'sunt cum tempora', 'completed': False},
 {'userId': 2, 'id': 38, 'title': 'totam quia non', 'completed': False},
 {'userId': 2,
  'id': 39,
  'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis',
  'completed': False},
 {'userId': 2,
  'id': 40,
  'title': 'totam atque quo nesciunt',
  'completed': True},
 {'userId': 3,
  'id': 41,
  'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit',
  'completed': False},
 {'userId': 3,
  'id': 42,
  'title': 'rerum perferendis error quia ut eveniet',
  'completed': False},
 {'userId': 3,
  'id': 43,
  'title': 'tempore ut sint quis recusandae',
  'completed': True},
 {'userId': 3,
  'id': 44,
  'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis',
  'completed': True},
 {'userId': 3,
  'id': 45,
  'title': 'velit soluta adipisci molestias reiciendis harum',
  'completed': False},
 {'userId': 3,
  'id': 46,
  'title': 'vel voluptatem repellat nihil placeat corporis',
  'completed': False},
 {'userId': 3,
  'id': 47,
  'title': 'nam qui rerum fugiat accusamus',
  'completed': False},
 {'userId': 3,
  'id': 48,
  'title': 'sit reprehenderit omnis quia',
  'completed': False},
 {'userId': 3,
  'id': 49,
  'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et',
  'completed': False},
 {'userId': 3,
  'id': 50,
  'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate',
  'completed': True},
 {'userId': 3,
  'id': 51,
  'title': 'distinctio exercitationem ab doloribus',
  'completed': False},
 {'userId': 3,
  'id': 52,
  'title': 'nesciunt dolorum quis recusandae ad pariatur ratione',
  'completed': False},
 {'userId': 3,
  'id': 53,
  'title': 'qui labore est occaecati recusandae aliquid quam',
  'completed': False},
 {'userId': 3,
  'id': 54,
  'title': 'quis et est ut voluptate quam dolor',
  'completed': True},
 {'userId': 3,
  'id': 55,
  'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione',
  'completed': True},
 {'userId': 3,
  'id': 56,
  'title': 'deleniti ea temporibus enim',
  'completed': True},
 {'userId': 3,
  'id': 57,
  'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia',
  'completed': False},
 {'userId': 3,
  'id': 58,
  'title': 'est dicta totam qui explicabo doloribus qui dignissimos',
  'completed': False},
 {'userId': 3,
  'id': 59,
  'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio',
  'completed': False},
 {'userId': 3,
  'id': 60,
  'title': 'et sequi qui architecto ut adipisci',
  'completed': True},
 {'userId': 4,
  'id': 61,
  'title': 'odit optio omnis qui sunt',
  'completed': True},
 {'userId': 4,
  'id': 62,
  'title': 'et placeat et tempore aspernatur sint numquam',
  'completed': False},
 {'userId': 4,
  'id': 63,
  'title': 'doloremque aut dolores quidem fuga qui nulla',
  'completed': True},
 {'userId': 4,
  'id': 64,
  'title': 'voluptas consequatur qui ut quia magnam nemo esse',
  'completed': False},
 {'userId': 4,
  'id': 65,
  'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni',
  'completed': False},
 {'userId': 4,
  'id': 66,
  'title': 'rerum eum molestias autem voluptatum sit optio',
  'completed': False},
 {'userId': 4,
  'id': 67,
  'title': 'quia voluptatibus voluptatem quos similique maiores repellat',
  'completed': False},
 {'userId': 4,
  'id': 68,
  'title': 'aut id perspiciatis voluptatem iusto',
  'completed': False},
 {'userId': 4,
  'id': 69,
  'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit',
  'completed': False},
 {'userId': 4,
  'id': 70,
  'title': 'ut sequi accusantium et mollitia delectus sunt',
  'completed': False},
 {'userId': 4, 'id': 71, 'title': 'aut velit saepe ullam', 'completed': False},
 {'userId': 4,
  'id': 72,
  'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum',
  'completed': False},
 {'userId': 4,
  'id': 73,
  'title': 'sint amet quia totam corporis qui exercitationem commodi',
  'completed': True},
 {'userId': 4,
  'id': 74,
  'title': 'expedita tempore nobis eveniet laborum maiores',
  'completed': False},
 {'userId': 4,
  'id': 75,
  'title': 'occaecati adipisci est possimus totam',
  'completed': False},
 {'userId': 4, 'id': 76, 'title': 'sequi dolorem sed', 'completed': True},
 {'userId': 4,
  'id': 77,
  'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at',
  'completed': False},
 {'userId': 4,
  'id': 78,
  'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat',
  'completed': False},
 {'userId': 4, 'id': 79, 'title': 'eum ipsa maxime ut', 'completed': True},
 {'userId': 4,
  'id': 80,
  'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur',
  'completed': True},
 {'userId': 5, 'id': 81, 'title': 'suscipit qui totam', 'completed': True},
 {'userId': 5,
  'id': 82,
  'title': 'voluptates eum voluptas et dicta',
  'completed': False},
 {'userId': 5,
  'id': 83,
  'title': 'quidem at rerum quis ex aut sit quam',
  'completed': True},
 {'userId': 5,
  'id': 84,
  'title': 'sunt veritatis ut voluptate',
  'completed': False},
 {'userId': 5, 'id': 85, 'title': 'et quia ad iste a', 'completed': True},
 {'userId': 5,
  'id': 86,
  'title': 'incidunt ut saepe autem',
  'completed': True},
 {'userId': 5,
  'id': 87,
  'title': 'laudantium quae eligendi consequatur quia et vero autem',
  'completed': True},
 {'userId': 5,
  'id': 88,
  'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium',
  'completed': False},
 {'userId': 5, 'id': 89, 'title': 'sequi ut omnis et', 'completed': True},
 {'userId': 5,
  'id': 90,
  'title': 'molestiae nisi accusantium tenetur dolorem et',
  'completed': True},
 {'userId': 5,
  'id': 91,
  'title': 'nulla quis consequatur saepe qui id expedita',
  'completed': True},
 {'userId': 5, 'id': 92, 'title': 'in omnis laboriosam', 'completed': True},
 {'userId': 5,
  'id': 93,
  'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint',
  'completed': True},
 {'userId': 5,
  'id': 94,
  'title': 'facilis modi saepe mollitia',
  'completed': False},
 {'userId': 5,
  'id': 95,
  'title': 'vel nihil et molestiae iusto assumenda nemo quo ut',
  'completed': True},
 {'userId': 5,
  'id': 96,
  'title': 'nobis suscipit ducimus enim asperiores voluptas',
  'completed': False},
 {'userId': 5,
  'id': 97,
  'title': 'dolorum laboriosam eos qui iure aliquam',
  'completed': False},
 {'userId': 5,
  'id': 98,
  'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus',
  'completed': True},
 {'userId': 5,
  'id': 99,
  'title': 'neque voluptates ratione',
  'completed': False},
 {'userId': 5,
  'id': 100,
  'title': 'excepturi a et neque qui expedita vel voluptate',
  'completed': False},
 {'userId': 6,
  'id': 101,
  'title': 'explicabo enim cumque porro aperiam occaecati minima',
  'completed': False},
 {'userId': 6, 'id': 102, 'title': 'sed ab consequatur', 'completed': False},
 {'userId': 6,
  'id': 103,
  'title': 'non sunt delectus illo nulla tenetur enim omnis',
  'completed': False},
 {'userId': 6,
  'id': 104,
  'title': 'excepturi non laudantium quo',
  'completed': False},
 {'userId': 6,
  'id': 105,
  'title': 'totam quia dolorem et illum repellat voluptas optio',
  'completed': True},
 {'userId': 6,
  'id': 106,
  'title': 'ad illo quis voluptatem temporibus',
  'completed': True},
 {'userId': 6,
  'id': 107,
  'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt',
  'completed': False},
 {'userId': 6,
  'id': 108,
  'title': 'a eos eaque nihil et exercitationem incidunt delectus',
  'completed': True},
 {'userId': 6,
  'id': 109,
  'title': 'autem temporibus harum quisquam in culpa',
  'completed': True},
 {'userId': 6, 'id': 110, 'title': 'aut aut ea corporis', 'completed': True},
 {'userId': 6,
  'id': 111,
  'title': 'magni accusantium labore et id quis provident',
  'completed': False},
 {'userId': 6,
  'id': 112,
  'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius',
  'completed': False},
 {'userId': 6,
  'id': 113,
  'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi',
  'completed': False},
 {'userId': 6,
  'id': 114,
  'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae',
  'completed': False},
 {'userId': 6, 'id': 115, 'title': 'sed et ea eum', 'completed': False},
 {'userId': 6,
  'id': 116,
  'title': 'ipsa dolores vel facilis ut',
  'completed': True},
 {'userId': 6,
  'id': 117,
  'title': 'sequi quae est et qui qui eveniet asperiores',
  'completed': False},
 {'userId': 6,
  'id': 118,
  'title': 'quia modi consequatur vero fugiat',
  'completed': False},
 {'userId': 6,
  'id': 119,
  'title': 'corporis ducimus ea perspiciatis iste',
  'completed': False},
 {'userId': 6,
  'id': 120,
  'title': 'dolorem laboriosam vel voluptas et aliquam quasi',
  'completed': False},
 {'userId': 7,
  'id': 121,
  'title': 'inventore aut nihil minima laudantium hic qui omnis',
  'completed': True},
 {'userId': 7,
  'id': 122,
  'title': 'provident aut nobis culpa',
  'completed': True},
 {'userId': 7,
  'id': 123,
  'title': 'esse et quis iste est earum aut impedit',
  'completed': False},
 {'userId': 7, 'id': 124, 'title': 'qui consectetur id', 'completed': False},
 {'userId': 7,
  'id': 125,
  'title': 'aut quasi autem iste tempore illum possimus',
  'completed': False},
 {'userId': 7,
  'id': 126,
  'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe',
  'completed': True},
 {'userId': 7,
  'id': 127,
  'title': 'voluptatem libero consectetur rerum ut',
  'completed': True},
 {'userId': 7,
  'id': 128,
  'title': 'eius omnis est qui voluptatem autem',
  'completed': False},
 {'userId': 7,
  'id': 129,
  'title': 'rerum culpa quis harum',
  'completed': False},
 {'userId': 7,
  'id': 130,
  'title': 'nulla aliquid eveniet harum laborum libero alias ut unde',
  'completed': True},
 {'userId': 7, 'id': 131, 'title': 'qui ea incidunt quis', 'completed': False},
 {'userId': 7,
  'id': 132,
  'title': 'qui molestiae voluptatibus velit iure harum quisquam',
  'completed': True},
 {'userId': 7,
  'id': 133,
  'title': 'et labore eos enim rerum consequatur sunt',
  'completed': True},
 {'userId': 7,
  'id': 134,
  'title': 'molestiae doloribus et laborum quod ea',
  'completed': False},
 {'userId': 7,
  'id': 135,
  'title': 'facere ipsa nam eum voluptates reiciendis vero qui',
  'completed': False},
 {'userId': 7,
  'id': 136,
  'title': 'asperiores illo tempora fuga sed ut quasi adipisci',
  'completed': False},
 {'userId': 7, 'id': 137, 'title': 'qui sit non', 'completed': False},
 {'userId': 7,
  'id': 138,
  'title': 'placeat minima consequatur rem qui ut',
  'completed': True},
 {'userId': 7,
  'id': 139,
  'title': 'consequatur doloribus id possimus voluptas a voluptatem',
  'completed': False},
 {'userId': 7,
  'id': 140,
  'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam',
  'completed': True},
 {'userId': 8,
  'id': 141,
  'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non',
  'completed': True},
 {'userId': 8,
  'id': 142,
  'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut',
  'completed': True},
 {'userId': 8,
  'id': 143,
  'title': 'eum non recusandae cupiditate animi',
  'completed': False},
 {'userId': 8,
  'id': 144,
  'title': 'ut eum exercitationem sint',
  'completed': False},
 {'userId': 8,
  'id': 145,
  'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam',
  'completed': False},
 {'userId': 8,
  'id': 146,
  'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam',
  'completed': True},
 {'userId': 8,
  'id': 147,
  'title': 'eum itaque quod reprehenderit et facilis dolor autem ut',
  'completed': True},
 {'userId': 8,
  'id': 148,
  'title': 'esse quas et quo quasi exercitationem',
  'completed': False},
 {'userId': 8,
  'id': 149,
  'title': 'animi voluptas quod perferendis est',
  'completed': False},
 {'userId': 8,
  'id': 150,
  'title': 'eos amet tempore laudantium fugit a',
  'completed': False},
 {'userId': 8,
  'id': 151,
  'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero',
  'completed': True},
 {'userId': 8,
  'id': 152,
  'title': 'odit eligendi recusandae doloremque cumque non',
  'completed': False},
 {'userId': 8,
  'id': 153,
  'title': 'ea aperiam consequatur qui repellat eos',
  'completed': False},
 {'userId': 8, 'id': 154, 'title': 'rerum non ex sapiente', 'completed': True},
 {'userId': 8,
  'id': 155,
  'title': 'voluptatem nobis consequatur et assumenda magnam',
  'completed': True},
 {'userId': 8,
  'id': 156,
  'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis',
  'completed': True},
 {'userId': 8,
  'id': 157,
  'title': 'dolorem veniam quisquam deserunt repellendus',
  'completed': True},
 {'userId': 8,
  'id': 158,
  'title': 'debitis vitae delectus et harum accusamus aut deleniti a',
  'completed': True},
 {'userId': 8,
  'id': 159,
  'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis',
  'completed': True},
 {'userId': 8,
  'id': 160,
  'title': 'et praesentium aliquam est',
  'completed': False},
 {'userId': 9,
  'id': 161,
  'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa',
  'completed': True},
 {'userId': 9,
  'id': 162,
  'title': 'omnis laboriosam molestias animi sunt dolore',
  'completed': True},
 {'userId': 9,
  'id': 163,
  'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit',
  'completed': False},
 {'userId': 9,
  'id': 164,
  'title': 'reprehenderit quos aut aut consequatur est sed',
  'completed': False},
 {'userId': 9,
  'id': 165,
  'title': 'fugiat perferendis sed aut quidem',
  'completed': False},
 {'userId': 9,
  'id': 166,
  'title': 'quos quo possimus suscipit minima ut',
  'completed': False},
 {'userId': 9,
  'id': 167,
  'title': 'et quis minus quo a asperiores molestiae',
  'completed': False},
 {'userId': 9,
  'id': 168,
  'title': 'recusandae quia qui sunt libero',
  'completed': False},
 {'userId': 9,
  'id': 169,
  'title': 'ea odio perferendis officiis',
  'completed': True},
 {'userId': 9,
  'id': 170,
  'title': 'quisquam aliquam quia doloribus aut',
  'completed': False},
 {'userId': 9,
  'id': 171,
  'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio',
  'completed': True},
 {'userId': 9,
  'id': 172,
  'title': 'et provident amet rerum consectetur et voluptatum',
  'completed': False},
 {'userId': 9,
  'id': 173,
  'title': 'harum ad aperiam quis',
  'completed': False},
 {'userId': 9, 'id': 174, 'title': 'similique aut quo', 'completed': False},
 {'userId': 9,
  'id': 175,
  'title': 'laudantium eius officia perferendis provident perspiciatis asperiores',
  'completed': True},
 {'userId': 9,
  'id': 176,
  'title': 'magni soluta corrupti ut maiores rem quidem',
  'completed': False},
 {'userId': 9,
  'id': 177,
  'title': 'et placeat temporibus voluptas est tempora quos quibusdam',
  'completed': False},
 {'userId': 9,
  'id': 178,
  'title': 'nesciunt itaque commodi tempore',
  'completed': True},
 {'userId': 9,
  'id': 179,
  'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo',
  'completed': True},
 {'userId': 9,
  'id': 180,
  'title': 'debitis nisi et dolorem repellat et',
  'completed': True},
 {'userId': 10,
  'id': 181,
  'title': 'ut cupiditate sequi aliquam fuga maiores',
  'completed': False},
 {'userId': 10,
  'id': 182,
  'title': 'inventore saepe cumque et aut illum enim',
  'completed': True},
 {'userId': 10,
  'id': 183,
  'title': 'omnis nulla eum aliquam distinctio',
  'completed': True},
 {'userId': 10,
  'id': 184,
  'title': 'molestias modi perferendis perspiciatis',
  'completed': False},
 {'userId': 10,
  'id': 185,
  'title': 'voluptates dignissimos sed doloribus animi quaerat aut',
  'completed': False},
 {'userId': 10,
  'id': 186,
  'title': 'explicabo odio est et',
  'completed': False},
 {'userId': 10,
  'id': 187,
  'title': 'consequuntur animi possimus',
  'completed': False},
 {'userId': 10, 'id': 188, 'title': 'vel non beatae est', 'completed': True},
 {'userId': 10,
  'id': 189,
  'title': 'culpa eius et voluptatem et',
  'completed': True},
 {'userId': 10,

In [186]:
with open("C://training/data/cd_catalog.xml","r") as ip:
    xml=etree.parse(ip)
    root=xml.getroot()
    for cd in root.findall("CD"):
        print(cd.find("TITLE").text)
        print(cd.find("ARTIST").text)
        print(cd.find("COUNTRY").text)
        print(cd.find("COMPANY").text)
        print(cd.find("PRICE").text)
        print(cd.find("YEAR").text)

Empire Burlesque
Bob Dylan
USA
Columbia
10.90
1985
Hide your heart
Bonnie Tyler
UK
CBS Records
9.90
1988
Greatest Hits
Dolly Parton
USA
RCA
9.90
1982
Still got the blues
Gary Moore
UK
Virgin records
10.20
1990
Eros
Eros Ramazzotti
EU
BMG
9.90
1997
One night only
Bee Gees
UK
Polydor
10.90
1998
Sylvias Mother
Dr.Hook
UK
CBS
8.10
1973
Maggie May
Rod Stewart
UK
Pickwick
8.50
1990
Romanza
Andrea Bocelli
EU
Polydor
10.80
1996
When a man loves a woman
Percy Sledge
USA
Atlantic
8.70
1987
Black angel
Savage Rose
EU
Mega
10.90
1995
1999 Grammy Nominees
Many
USA
Grammy
10.20
1999
For the good times
Kenny Rogers
UK
Mucik Master
8.70
1995
Big Willie style
Will Smith
USA
Columbia
9.90
1997
Tupelo Honey
Van Morrison
UK
Polydor
8.20
1971
Soulsville
Jorn Hoel
Norway
WEA
7.90
1996
The very best of
Cat Stevens
UK
Island
8.90
1990
Stop
Sam Brown
UK
A and M
8.90
1988
Bridge of Spies
T'Pau
UK
Siren
7.90
1987
Private Dancer
Tina Turner
UK
Capitol
8.90
1983
Midt om natten
Kim Larsen
EU
Medley
7.80
1983
Pavarotti Gala Concert
Luciano Pavarotti
UK
DECCA
9.90
1991
The dock of the bay
Otis Redding
USA
Stax Records
7.90
1968
Picture book
Simply Red
EU
Elektra
7.20
1985
Red
The Communards
UK
London
7.80
1987
Unchain my heart
Joe Cocker
USA
EMI
8.20
1987

In [187]:
xmllist=[]
columnList=["TITLE","ARTIST","COUNTRY","COMPANY","PRICE"]
with open("C://training/data/cd_catalog.xml","r") as ip:
    xml=etree.parse(ip)
    root=xml.getroot()
    for cd in root.findall("CD"):
        xmlDict = {}
        for column in columnList:
            xmlDict[column]=cd.find(column).text
        xmllist.append(xmlDict)

In [189]:
with open("C://training/data/cd.csv","w",newline='') as op:
    dw = csv.DictWriter(op,columnList)
    dw.writeheader()
    dw.writerows(xmllist)

In [190]:
jsondata=requests.get("https://jsonplaceholder.typicode.com/todos/").json()

In [191]:
with open("C://training/data//todos.csv","w",newline="") as op:
    dw=csv.DictWriter(op,["id","userId","title","completed"])
    dw.writeheader()
    dw.writerows(jsondata)

In [193]:
import json
with open("C://training//data/download.json","r") as ip:
    jsondatalst=json.load(ip)
    print(jsondatalst)

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}, {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True}, {'userId': 1, 'id': 5, 'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum', 'completed': False}, {'userId': 1, 'id': 6, 'title': 'qui ullam ratione quibusdam voluptatem quia omnis', 'completed': False}, {'userId': 1, 'id': 7, 'title': 'illo expedita consequatur quia in', 'completed': False}, {'userId': 1, 'id': 8, 'title': 'quo adipisci enim quam ut ab', 'completed': True}, {'userId': 1, 'id': 9, 'title': 'molestiae perspiciatis ipsa', 'completed': False}, {'userId': 1, 'id': 10, 'title': 'illo est ratione doloremque quia maiores aut', 'completed': True}, {'userId': 1, 'id': 11, 'title': 'vero rerum temporibus dolor', 'completed': True}, {'userId': 1, 'id': 12, 'title': 'ipsa repellendus fugit nisi', 'completed': True}, {'userId': 1, 'id': 13, 'title': 'et doloremque nulla', 'completed': False}, {'userId': 1, 'id': 14, 'title': 'repellendus sunt dolores architecto voluptatum', 'completed': True}, {'userId': 1, 'id': 15, 'title': 'ab voluptatum amet voluptas', 'completed': True}, {'userId': 1, 'id': 16, 'title': 'accusamus eos facilis sint et aut voluptatem', 'completed': True}, {'userId': 1, 'id': 17, 'title': 'quo laboriosam deleniti aut qui', 'completed': True}, {'userId': 1, 'id': 18, 'title': 'dolorum est consequatur ea mollitia in culpa', 'completed': False}, {'userId': 1, 'id': 19, 'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil', 'completed': True}, {'userId': 1, 'id': 20, 'title': 'ullam nobis libero sapiente ad optio sint', 'completed': True}, {'userId': 2, 'id': 21, 'title': 'suscipit repellat esse quibusdam voluptatem incidunt', 'completed': False}, {'userId': 2, 'id': 22, 'title': 'distinctio vitae autem nihil ut molestias quo', 'completed': True}, {'userId': 2, 'id': 23, 'title': 'et itaque necessitatibus maxime molestiae qui quas velit', 'completed': False}, {'userId': 2, 'id': 24, 'title': 'adipisci non ad dicta qui amet quaerat doloribus ea', 'completed': False}, {'userId': 2, 'id': 25, 'title': 'voluptas quo tenetur perspiciatis explicabo natus', 'completed': True}, {'userId': 2, 'id': 26, 'title': 'aliquam aut quasi', 'completed': True}, {'userId': 2, 'id': 27, 'title': 'veritatis pariatur delectus', 'completed': True}, {'userId': 2, 'id': 28, 'title': 'nesciunt totam sit blanditiis sit', 'completed': False}, {'userId': 2, 'id': 29, 'title': 'laborum aut in quam', 'completed': False}, {'userId': 2, 'id': 30, 'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis', 'completed': True}, {'userId': 2, 'id': 31, 'title': 'repudiandae totam in est sint facere fuga', 'completed': False}, {'userId': 2, 'id': 32, 'title': 'earum doloribus ea doloremque quis', 'completed': False}, {'userId': 2, 'id': 33, 'title': 'sint sit aut vero', 'completed': False}, {'userId': 2, 'id': 34, 'title': 'porro aut necessitatibus eaque distinctio', 'completed': False}, {'userId': 2, 'id': 35, 'title': 'repellendus veritatis molestias dicta incidunt', 'completed': True}, {'userId': 2, 'id': 36, 'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad', 'completed': True}, {'userId': 2, 'id': 37, 'title': 'sunt cum tempora', 'completed': False}, {'userId': 2, 'id': 38, 'title': 'totam quia non', 'completed': False}, {'userId': 2, 'id': 39, 'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis', 'completed': False}, {'userId': 2, 'id': 40, 'title': 'totam atque quo nesciunt', 'completed': True}, {'userId': 3, 'id': 41, 'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit', 'completed': False}, {'userId': 3, 'id': 42, 'title': 'rerum perferendis error quia ut eveniet', 'completed': False}, {'userId': 3, 'id': 43, 'title': 'tempore ut sint quis recusandae', 'completed': True}, {'userId': 3, 'id': 44, 'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis', 'completed': True}, {'userId': 3, 'id': 45, 'title': 'velit soluta adipisci molestias reiciendis harum', 'completed': False}, {'userId': 3, 'id': 46, 'title': 'vel voluptatem repellat nihil placeat corporis', 'completed': False}, {'userId': 3, 'id': 47, 'title': 'nam qui rerum fugiat accusamus', 'completed': False}, {'userId': 3, 'id': 48, 'title': 'sit reprehenderit omnis quia', 'completed': False}, {'userId': 3, 'id': 49, 'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et', 'completed': False}, {'userId': 3, 'id': 50, 'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate', 'completed': True}, {'userId': 3, 'id': 51, 'title': 'distinctio exercitationem ab doloribus', 'completed': False}, {'userId': 3, 'id': 52, 'title': 'nesciunt dolorum quis recusandae ad pariatur ratione', 'completed': False}, {'userId': 3, 'id': 53, 'title': 'qui labore est occaecati recusandae aliquid quam', 'completed': False}, {'userId': 3, 'id': 54, 'title': 'quis et est ut voluptate quam dolor', 'completed': True}, {'userId': 3, 'id': 55, 'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione', 'completed': True}, {'userId': 3, 'id': 56, 'title': 'deleniti ea temporibus enim', 'completed': True}, {'userId': 3, 'id': 57, 'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia', 'completed': False}, {'userId': 3, 'id': 58, 'title': 'est dicta totam qui explicabo doloribus qui dignissimos', 'completed': False}, {'userId': 3, 'id': 59, 'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio', 'completed': False}, {'userId': 3, 'id': 60, 'title': 'et sequi qui architecto ut adipisci', 'completed': True}, {'userId': 4, 'id': 61, 'title': 'odit optio omnis qui sunt', 'completed': True}, {'userId': 4, 'id': 62, 'title': 'et placeat et tempore aspernatur sint numquam', 'completed': False}, {'userId': 4, 'id': 63, 'title': 'doloremque aut dolores quidem fuga qui nulla', 'completed': True}, {'userId': 4, 'id': 64, 'title': 'voluptas consequatur qui ut quia magnam nemo esse', 'completed': False}, {'userId': 4, 'id': 65, 'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni', 'completed': False}, {'userId': 4, 'id': 66, 'title': 'rerum eum molestias autem voluptatum sit optio', 'completed': False}, {'userId': 4, 'id': 67, 'title': 'quia voluptatibus voluptatem quos similique maiores repellat', 'completed': False}, {'userId': 4, 'id': 68, 'title': 'aut id perspiciatis voluptatem iusto', 'completed': False}, {'userId': 4, 'id': 69, 'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit', 'completed': False}, {'userId': 4, 'id': 70, 'title': 'ut sequi accusantium et mollitia delectus sunt', 'completed': False}, {'userId': 4, 'id': 71, 'title': 'aut velit saepe ullam', 'completed': False}, {'userId': 4, 'id': 72, 'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum', 'completed': False}, {'userId': 4, 'id': 73, 'title': 'sint amet quia totam corporis qui exercitationem commodi', 'completed': True}, {'userId': 4, 'id': 74, 'title': 'expedita tempore nobis eveniet laborum maiores', 'completed': False}, {'userId': 4, 'id': 75, 'title': 'occaecati adipisci est possimus totam', 'completed': False}, {'userId': 4, 'id': 76, 'title': 'sequi dolorem sed', 'completed': True}, {'userId': 4, 'id': 77, 'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at', 'completed': False}, {'userId': 4, 'id': 78, 'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat', 'completed': False}, {'userId': 4, 'id': 79, 'title': 'eum ipsa maxime ut', 'completed': True}, {'userId': 4, 'id': 80, 'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur', 'completed': True}, {'userId': 5, 'id': 81, 'title': 'suscipit qui totam', 'completed': True}, {'userId': 5, 'id': 82, 'title': 'voluptates eum voluptas et dicta', 'completed': False}, {'userId': 5, 'id': 83, 'title': 'quidem at rerum quis ex aut sit quam', 'completed': True}, {'userId': 5, 'id': 84, 'title': 'sunt veritatis ut voluptate', 'completed': False}, {'userId': 5, 'id': 85, 'title': 'et quia ad iste a', 'completed': True}, {'userId': 5, 'id': 86, 'title': 'incidunt ut saepe autem', 'completed': True}, {'userId': 5, 'id': 87, 'title': 'laudantium quae eligendi consequatur quia et vero autem', 'completed': True}, {'userId': 5, 'id': 88, 'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium', 'completed': False}, {'userId': 5, 'id': 89, 'title': 'sequi ut omnis et', 'completed': True}, {'userId': 5, 'id': 90, 'title': 'molestiae nisi accusantium tenetur dolorem et', 'completed': True}, {'userId': 5, 'id': 91, 'title': 'nulla quis consequatur saepe qui id expedita', 'completed': True}, {'userId': 5, 'id': 92, 'title': 'in omnis laboriosam', 'completed': True}, {'userId': 5, 'id': 93, 'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint', 'completed': True}, {'userId': 5, 'id': 94, 'title': 'facilis modi saepe mollitia', 'completed': False}, {'userId': 5, 'id': 95, 'title': 'vel nihil et molestiae iusto assumenda nemo quo ut', 'completed': True}, {'userId': 5, 'id': 96, 'title': 'nobis suscipit ducimus enim asperiores voluptas', 'completed': False}, {'userId': 5, 'id': 97, 'title': 'dolorum laboriosam eos qui iure aliquam', 'completed': False}, {'userId': 5, 'id': 98, 'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus', 'completed': True}, {'userId': 5, 'id': 99, 'title': 'neque voluptates ratione', 'completed': False}, {'userId': 5, 'id': 100, 'title': 'excepturi a et neque qui expedita vel voluptate', 'completed': False}, {'userId': 6, 'id': 101, 'title': 'explicabo enim cumque porro aperiam occaecati minima', 'completed': False}, {'userId': 6, 'id': 102, 'title': 'sed ab consequatur', 'completed': False}, {'userId': 6, 'id': 103, 'title': 'non sunt delectus illo nulla tenetur enim omnis', 'completed': False}, {'userId': 6, 'id': 104, 'title': 'excepturi non laudantium quo', 'completed': False}, {'userId': 6, 'id': 105, 'title': 'totam quia dolorem et illum repellat voluptas optio', 'completed': True}, {'userId': 6, 'id': 106, 'title': 'ad illo quis voluptatem temporibus', 'completed': True}, {'userId': 6, 'id': 107, 'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt', 'completed': False}, {'userId': 6, 'id': 108, 'title': 'a eos eaque nihil et exercitationem incidunt delectus', 'completed': True}, {'userId': 6, 'id': 109, 'title': 'autem temporibus harum quisquam in culpa', 'completed': True}, {'userId': 6, 'id': 110, 'title': 'aut aut ea corporis', 'completed': True}, {'userId': 6, 'id': 111, 'title': 'magni accusantium labore et id quis provident', 'completed': False}, {'userId': 6, 'id': 112, 'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius', 'completed': False}, {'userId': 6, 'id': 113, 'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi', 'completed': False}, {'userId': 6, 'id': 114, 'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae', 'completed': False}, {'userId': 6, 'id': 115, 'title': 'sed et ea eum', 'completed': False}, {'userId': 6, 'id': 116, 'title': 'ipsa dolores vel facilis ut', 'completed': True}, {'userId': 6, 'id': 117, 'title': 'sequi quae est et qui qui eveniet asperiores', 'completed': False}, {'userId': 6, 'id': 118, 'title': 'quia modi consequatur vero fugiat', 'completed': False}, {'userId': 6, 'id': 119, 'title': 'corporis ducimus ea perspiciatis iste', 'completed': False}, {'userId': 6, 'id': 120, 'title': 'dolorem laboriosam vel voluptas et aliquam quasi', 'completed': False}, {'userId': 7, 'id': 121, 'title': 'inventore aut nihil minima laudantium hic qui omnis', 'completed': True}, {'userId': 7, 'id': 122, 'title': 'provident aut nobis culpa', 'completed': True}, {'userId': 7, 'id': 123, 'title': 'esse et quis iste est earum aut impedit', 'completed': False}, {'userId': 7, 'id': 124, 'title': 'qui consectetur id', 'completed': False}, {'userId': 7, 'id': 125, 'title': 'aut quasi autem iste tempore illum possimus', 'completed': False}, {'userId': 7, 'id': 126, 'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe', 'completed': True}, {'userId': 7, 'id': 127, 'title': 'voluptatem libero consectetur rerum ut', 'completed': True}, {'userId': 7, 'id': 128, 'title': 'eius omnis est qui voluptatem autem', 'completed': False}, {'userId': 7, 'id': 129, 'title': 'rerum culpa quis harum', 'completed': False}, {'userId': 7, 'id': 130, 'title': 'nulla aliquid eveniet harum laborum libero alias ut unde', 'completed': True}, {'userId': 7, 'id': 131, 'title': 'qui ea incidunt quis', 'completed': False}, {'userId': 7, 'id': 132, 'title': 'qui molestiae voluptatibus velit iure harum quisquam', 'completed': True}, {'userId': 7, 'id': 133, 'title': 'et labore eos enim rerum consequatur sunt', 'completed': True}, {'userId': 7, 'id': 134, 'title': 'molestiae doloribus et laborum quod ea', 'completed': False}, {'userId': 7, 'id': 135, 'title': 'facere ipsa nam eum voluptates reiciendis vero qui', 'completed': False}, {'userId': 7, 'id': 136, 'title': 'asperiores illo tempora fuga sed ut quasi adipisci', 'completed': False}, {'userId': 7, 'id': 137, 'title': 'qui sit non', 'completed': False}, {'userId': 7, 'id': 138, 'title': 'placeat minima consequatur rem qui ut', 'completed': True}, {'userId': 7, 'id': 139, 'title': 'consequatur doloribus id possimus voluptas a voluptatem', 'completed': False}, {'userId': 7, 'id': 140, 'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam', 'completed': True}, {'userId': 8, 'id': 141, 'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non', 'completed': True}, {'userId': 8, 'id': 142, 'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut', 'completed': True}, {'userId': 8, 'id': 143, 'title': 'eum non recusandae cupiditate animi', 'completed': False}, {'userId': 8, 'id': 144, 'title': 'ut eum exercitationem sint', 'completed': False}, {'userId': 8, 'id': 145, 'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam', 'completed': False}, {'userId': 8, 'id': 146, 'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam', 'completed': True}, {'userId': 8, 'id': 147, 'title': 'eum itaque quod reprehenderit et facilis dolor autem ut', 'completed': True}, {'userId': 8, 'id': 148, 'title': 'esse quas et quo quasi exercitationem', 'completed': False}, {'userId': 8, 'id': 149, 'title': 'animi voluptas quod perferendis est', 'completed': False}, {'userId': 8, 'id': 150, 'title': 'eos amet tempore laudantium fugit a', 'completed': False}, {'userId': 8, 'id': 151, 'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero', 'completed': True}, {'userId': 8, 'id': 152, 'title': 'odit eligendi recusandae doloremque cumque non', 'completed': False}, {'userId': 8, 'id': 153, 'title': 'ea aperiam consequatur qui repellat eos', 'completed': False}, {'userId': 8, 'id': 154, 'title': 'rerum non ex sapiente', 'completed': True}, {'userId': 8, 'id': 155, 'title': 'voluptatem nobis consequatur et assumenda magnam', 'completed': True}, {'userId': 8, 'id': 156, 'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis', 'completed': True}, {'userId': 8, 'id': 157, 'title': 'dolorem veniam quisquam deserunt repellendus', 'completed': True}, {'userId': 8, 'id': 158, 'title': 'debitis vitae delectus et harum accusamus aut deleniti a', 'completed': True}, {'userId': 8, 'id': 159, 'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis', 'completed': True}, {'userId': 8, 'id': 160, 'title': 'et praesentium aliquam est', 'completed': False}, {'userId': 9, 'id': 161, 'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa', 'completed': True}, {'userId': 9, 'id': 162, 'title': 'omnis laboriosam molestias animi sunt dolore', 'completed': True}, {'userId': 9, 'id': 163, 'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit', 'completed': False}, {'userId': 9, 'id': 164, 'title': 'reprehenderit quos aut aut consequatur est sed', 'completed': False}, {'userId': 9, 'id': 165, 'title': 'fugiat perferendis sed aut quidem', 'completed': False}, {'userId': 9, 'id': 166, 'title': 'quos quo possimus suscipit minima ut', 'completed': False}, {'userId': 9, 'id': 167, 'title': 'et quis minus quo a asperiores molestiae', 'completed': False}, {'userId': 9, 'id': 168, 'title': 'recusandae quia qui sunt libero', 'completed': False}, {'userId': 9, 'id': 169, 'title': 'ea odio perferendis officiis', 'completed': True}, {'userId': 9, 'id': 170, 'title': 'quisquam aliquam quia doloribus aut', 'completed': False}, {'userId': 9, 'id': 171, 'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio', 'completed': True}, {'userId': 9, 'id': 172, 'title': 'et provident amet rerum consectetur et voluptatum', 'completed': False}, {'userId': 9, 'id': 173, 'title': 'harum ad aperiam quis', 'completed': False}, {'userId': 9, 'id': 174, 'title': 'similique aut quo', 'completed': False}, {'userId': 9, 'id': 175, 'title': 'laudantium eius officia perferendis provident perspiciatis asperiores', 'completed': True}, {'userId': 9, 'id': 176, 'title': 'magni soluta corrupti ut maiores rem quidem', 'completed': False}, {'userId': 9, 'id': 177, 'title': 'et placeat temporibus voluptas est tempora quos quibusdam', 'completed': False}, {'userId': 9, 'id': 178, 'title': 'nesciunt itaque commodi tempore', 'completed': True}, {'userId': 9, 'id': 179, 'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo', 'completed': True}, {'userId': 9, 'id': 180, 'title': 'debitis nisi et dolorem repellat et', 'completed': True}, {'userId': 10, 'id': 181, 'title': 'ut cupiditate sequi aliquam fuga maiores', 'completed': False}, {'userId': 10, 'id': 182, 'title': 'inventore saepe cumque et aut illum enim', 'completed': True}, {'userId': 10, 'id': 183, 'title': 'omnis nulla eum aliquam distinctio', 'completed': True}, {'userId': 10, 'id': 184, 'title': 'molestias modi perferendis perspiciatis', 'completed': False}, {'userId': 10, 'id': 185, 'title': 'voluptates dignissimos sed doloribus animi quaerat aut', 'completed': False}, {'userId': 10, 'id': 186, 'title': 'explicabo odio est et', 'completed': False}, {'userId': 10, 'id': 187, 'title': 'consequuntur animi possimus', 'completed': False}, {'userId': 10, 'id': 188, 'title': 'vel non beatae est', 'completed': True}, {'userId': 10, 'id': 189, 'title': 'culpa eius et voluptatem et', 'completed': True}, {'userId': 10, 'id': 190, 'title': 'accusamus sint iusto et voluptatem exercitationem', 'completed': True}, {'userId': 10, 'id': 191, 'title': 'temporibus atque distinctio omnis eius impedit tempore molestias pariatur', 'completed': True}, {'userId': 10, 'id': 192, 'title': 'ut quas possimus exercitationem sint voluptates', 'completed': False}, {'userId': 10, 'id': 193, 'title': 'rerum debitis voluptatem qui eveniet tempora distinctio a', 'completed': True}, {'userId': 10, 'id': 194, 'title': 'sed ut vero sit molestiae', 'completed': False}, {'userId': 10, 'id': 195, 'title': 'rerum ex veniam mollitia voluptatibus pariatur', 'completed': True}, {'userId': 10, 'id': 196, 'title': 'consequuntur aut ut fugit similique', 'completed': True}, {'userId': 10, 'id': 197, 'title': 'dignissimos quo nobis earum saepe', 'completed': True}, {'userId': 10, 'id': 198, 'title': 'quis eius est sint explicabo', 'completed': True}, {'userId': 10, 'id': 199, 'title': 'numquam repellendus a magnam', 'completed': True}, {'userId': 10, 'id': 200, 'title': 'ipsam aperiam voluptates qui', 'completed': False}]

In [195]:
with open("C://training/data//todos1.csv","w",newline="") as op:
    dw=csv.DictWriter(op,["id","userId","title","completed"])
    dw.writeheader()
    dw.writerows(jsondatalst)

In [196]:
#Pandas 3 rd party module using which ETL

In [197]:
pip install pandas

Requirement already satisfied: pandas in c:\python311\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\python311\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [198]:
import pandas as pd

In [199]:
df=pd.read_xml("C://training//data/cd_catalog.xml")

In [200]:
df.to_csv("C://training//data//cd1.csv")

In [201]:
df.to_excel("C://training//data//cd.xlsx")

In [202]:
df.to_json("C://training//data//cd.json")

In [203]:
df1=pd.read_csv("C://training//data//cd1.csv")

In [205]:
df1.head(10)

,Unnamed: 0,TITLE,ARTIST,COUNTRY,COMPANY,PRICE,YEAR
0,0,Empire Burlesque,Bob Dylan,USA,Columbia,10.9,1985
1,1,Hide your heart,Bonnie Tyler,UK,CBS Records,9.9,1988
2,2,Greatest Hits,Dolly Parton,USA,RCA,9.9,1982
3,3,Still got the blues,Gary Moore,UK,Virgin records,10.2,1990
4,4,Eros,Eros Ramazzotti,EU,BMG,9.9,1997
5,5,One night only,Bee Gees,UK,Polydor,10.9,1998
6,6,Sylvias Mother,Dr.Hook,UK,CBS,8.1,1973
7,7,Maggie May,Rod Stewart,UK,Pickwick,8.5,1990
8,8,Romanza,Andrea Bocelli,EU,Polydor,10.8,1996
9,9,When a man loves a woman,Percy Sledge,USA,Atlantic,8.7,1987

In [206]:
iris=pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [207]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [208]:
iris.to_xml("C://training//data//iris.xml")

In [209]:
iris.columns

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [210]:
iris.shape

(150, 5)

In [211]:
iris['sepal.length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [212]:
iris[['sepal.length','sepal.width']]

     sepal.length  sepal.width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [213]:
iris['sepal.length'].sum()

np.float64(876.5)

In [214]:
iris['sepal.length'].mean()

np.float64(5.843333333333334)

In [215]:
iris['sepal.length'].std()

np.float64(0.828066127977863)

In [216]:
iris['sepal.length'].median()

np.float64(5.8)

In [217]:
iris.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [218]:
students=pd.read_csv("C://training//data/sam.txt")

In [219]:
course=pd.read_csv("C://training//data/course.txt")

In [220]:
students

   rollNo   name  age  course
0       1    Raj   23     1.0
1       2  Rahul   36     2.0
2       3  Vijay   46     NaN

In [222]:
course

   coursed coursename
0        1         IT
1        2       EXTC
2        3       COMP

In [223]:
res1=pd.merge(students,course,left_on="course",right_on="coursed",how="inner")

In [224]:
res1

   rollNo   name  age  course  coursed coursename
0       1    Raj   23     1.0        1         IT
1       2  Rahul   36     2.0        2       EXTC

In [225]:
res1=pd.merge(students,course,left_on="course",right_on="coursed",how="left")

In [226]:
res1

   rollNo   name  age  course  coursed coursename
0       1    Raj   23     1.0      1.0         IT
1       2  Rahul   36     2.0      2.0       EXTC
2       3  Vijay   46     NaN      NaN        NaN

In [227]:
res1.to_excel("C://training//data//1.xlsx")

In [229]:
res1.columns

Index(['rollNo', 'name', 'age', 'course', 'coursed', 'coursename'], dtype='object')

In [230]:
res.fillna(0)

   rollNo   name  age  course  coursed coursename
0       1    Raj   23     1.0      1.0         IT
1       2  Rahul   36     2.0      2.0       EXTC
2       3  Vijay   46     0.0      0.0          0

In [234]:
res1

   rollNo   name  age  course  coursed coursename
0       1    Raj   23     1.0      1.0         IT
1       2  Rahul   36     2.0      2.0       EXTC
2       3  Vijay   46     NaN      NaN        NaN

In [237]:
res1=res1.reset_index()

   index  rollNo   name  age  course  coursed coursename
0      0       1    Raj   23     1.0      1.0         IT
1      1       2  Rahul   36     2.0      2.0       EXTC
2      2       3  Vijay   46     NaN      NaN        NaN

In [239]:
#Except
#try except

try:
    n1=int(input("Enter number"))
    print("n1",n1)
except Exception as e:
    print("Some error",e)

Enter number A

Some error invalid literal for int() with base 10: 'A'

In [241]:
#Except
#try except
try:
    n1=int(input("Enter number"))
    print("n1",n1)
    n2=int(input("Enter number"))
    print("n2",n2)
    res =n1/n2
    print("res",res)
except ValueError as ve:
    print("Error in conversion",ve)
except Exception as e:
    print("Some error",e)

Enter number A

Error in conversion invalid literal for int() with base 10: 'A'

In [242]:
try:
    password1=input("Enter password")
    password2=input("Enter password again")
    if password1 != password2:
        raise Exception("Passwords are not equal")
except Exception as e:
    print("Some exception",e)

Enter password 33
Enter password again 44

Some exception Passwords are not equal

In [243]:
class PasswordNotEqual(Exception):
    pass

In [244]:
try:
    password1=input("Enter password")
    password2=input("Enter password again")
    if password1 != password2:
        raise PasswordNotEqual("Passwords are not equal")
except PasswordNotEqual as pe:
    print("Password issue",pe)
except Exception as e:
    print("Some exception",e)

Enter password 11
Enter password again 22

Password issue Passwords are not equal

In [245]:
#input as age
#age <0 or > 120  InvalidAgeException

In [246]:
class AgeException(Exception):
    pass

In [248]:
try:
    age=int(input("Enter age"))
    if age < 0 or age > 120:
        raise AgeException(str(age) +" is invalid")
except AgeException as ae:
    print("Age issue",ae)
except Exception as ex:
    print("Exception",ex)

Enter age -1

Age issue -1 is invalid