In [ ]:
#Python is an object oriented programming language
#Create classes in python
#create classes and we can create objects
#Class ---> entity
#class ----> attributes/properties
#----------->functions/method
#Class ---template
#1 name Raj

In [1]:
#__init__ --constructor
#properties are created/iniliazed within constructor
#Any function within a class will have self as a first argument
class Student:
    #constructor
    def __init__(self,rollNo,name):
        self.rollNo=rollNo
        self.name=name
    def display(self):
        print("Roll no is",self.rollNo)
        print("Name is",self.name)

In [2]:
s1 = Student(1,"Raj")

In [3]:
s1.display()

Roll no is 1
Name is Raj

In [4]:
s2=Student(2,"Vijay")

In [5]:
s2.display()

Roll no is 2
Name is Vijay

In [6]:
class Sample:
    def hello(self):
        print("Hello from us")

In [7]:
s1=Sample()

In [8]:
s1.hello()

Hello from us

In [9]:
class Calculator:
    def __init__(self,n1,n2):
        self.n1=n1
        self.n2=n2
        self.res=0
    def add(self):
        self.res=self.n1+self.n2
    def sub(self):
        self.res=self.n1-self.n2
    def mul(self):
        self.res=self.n1*self.n2
    def div(self):
        self.res = self.n1/self.n2

In [10]:
c1=Calculator(10,2)

In [11]:
c1.add()

In [12]:
c1.res

12

In [13]:
c1.sub()

In [14]:
c1.res

8

In [15]:
class Calculator2:
    def add(self,a,b):
        return a+b
    def sub(self,a,b):
        return a-b
    def mul(self,a,b):
        return a*b
    def div(self,a,b):
        return a/b

In [16]:
c1=Calculator2()

In [17]:
c1.add(22,33)

55

In [18]:
class Sample1:
    def __init__(self,a,b):
        self.a=a
        self.b=b

In [19]:
s1=Sample1(10,20)

In [20]:
s1.a

10

In [21]:
s1.b

20

In [22]:
s1.c=13#Dynamic variables

In [23]:
s1.c

13

In [24]:
class Sample3:#Loosely 
    __slots__=["n1","n2"]#indicate what variables can be created
    def __init__(self,n1,n2):
        self.n1=n1
        self.n2=n2

In [25]:
s3=Sample3(10,20)

In [26]:
s3.n1

10

In [27]:
s3.n2

20

In [28]:
s3.n3=100

AttributeError: 'Sample3' object has no attribute 'n3'

In [29]:
class Sample4:
    def __init__(self,n1,n2=10):
        self.n1=n1
        self.n2=n2

In [30]:
s1=Sample4(20)

In [31]:
s1.n1

20

In [32]:
s1.n2

10

In [33]:
s2=Sample4(20,30)

In [34]:
s2.n1

20

In [35]:
s2.n2

30

In [36]:
class Emp:
    def __init__(self,empId,empName):
        self.empId=empId
        self.empName=empName
    def __str__(self):
        return "Emp id {} Emp name {}".format(self.empId,self.empName)

In [37]:
e1=Emp(11,"Raj")

In [38]:
print(e1)

Emp id 11 Emp name Raj

In [39]:
str(e1)

'Emp id 11 Emp name Raj'

In [40]:
class Parent1:
    def __init__(self,n1):
        self.n1=n1
    def display(self):
        print("Value of n1 is",self.n1)

In [46]:
class Child1(Parent1):
    def __init__(self,n1,n2):
        Parent1.__init__(self,n1)
        self.n2=n2
    def display2(self):
        print("n1",self.n1)
        print("n2",self.n2)

In [47]:
c1=Child1(10,20)

In [48]:
c1.n1

10

In [49]:
c1.n2

20

In [45]:
c1.display()

Value of n1 is 10

In [50]:
c1.display2()

n1 10
n2 20

In [51]:
class Parent2:
    def __init__(self,n1):
        self.n1=n1
    def display(self):
        print("From Parent2--->",self.n1)

In [52]:
class Parent3:
    def __init__(self,n2):
        self.n2=n2
    def display(self):
        print("From Parent3--->",self.n2)

In [53]:
class Child2(Parent2,Parent3):#sequence of inheritance is responsible for resolving ambiguity
    def __init__(self,n1,n2):
        Parent2.__init__(self,n1)
        Parent3.__init__(self,n2)

In [54]:
c2=Child2(33,44)

In [55]:
c2.display()

From Parent2---> 33

In [62]:
class Complex:
    def __init__(self,real,img):
        self.real=real
        self.img=img
    def add(self,other):
        real =self.real+other.real
        img=self.img+other.img
        return Complex(real,img)
    def __add__(self,other):
        real =self.real+other.real
        img=self.img+other.img
        return Complex(real,img)   
    def __sub__(self,other):
        real =self.real-other.real
        img=self.img-other.img
        return Complex(real,img) 
    def __str__(self):
        return "Real {} Img {}".format(self.real,self.img)

In [63]:
c1 =Complex(10,20)
c2 = Complex(30,40)
c3=c1.add(c2)
print(c3)

Real 40 Img 60

In [64]:
c3=c1+c2

In [66]:
print(c3)

Real 40 Img 60

In [67]:
str(c3)

'Real 40 Img 60'

In [68]:
c3=c1-c2
print(c3)

Real -20 Img -20

In [ ]:
Arithmetic Operators:
+: __add__(self, other)
-: __sub__(self, other)
*: __mul__(self, other)
/: __truediv__(self, other)
//: __floordiv__(self, other)
%: __mod__(self, other)
**: __pow__(self, other)
Assignment Operators:
+=: __iadd__(self, other)
- =: __isub__(self, other)
* =: __imul__(self, other)
/ =: __itruediv__(self, other)
// =: __ifloordiv__(self, other)
% =: __imod__(self, other)
**=: __ipow__(self, other)
Comparison Operators:
==: __eq__(self, other)
!=: __ne__(self, other)
<: __lt__(self, other)
>: __gt__(self, other)
<=: __le__(self, other)
>=: __ge__(self, other)
Bitwise Operators:
&: __and__(self, other)
|: __or__(self, other)
^: __xor__(self, other)
~: __invert__(self) (unary)
<<: __lshift__(self, other)
>>: __rshift__(self, other)
Other Useful Special Methods:
len(): __len__(self)
str(): __str__(self)
repr(): __repr__(self)
in: __contains__(self, item)
[] (indexing/slicing): __getitem__(self, key), __setitem__(self, key, value), __delitem__(self, key)

In [76]:
class Point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return "x {} y{}".format(self.x,self.y)
    def __eq__(self,other):
        m1=self.x*self.x +self.y*self.y 
        m2=other.x*other.x+other.y*other.y
        print("equal")
        return m1==m2
    def __gt__(self,other):
        m1=self.x*self.x +self.y*self.y 
        m2=other.x*other.x+other.y*other.y
        print("greater")
        return m1>m2   
    def __ge__(self,other):
        m1=self.x*self.x +self.y*self.y 
        m2=other.x*other.x+other.y*other.y
        print("greate equal")
        return m1>=m2
    def __lt__(self,other):
        m1=self.x*self.x +self.y*self.y 
        m2=other.x*other.x+other.y*other.y
        print("less than")
        return m1<m2  
    def __le__(self,other):
        m1=self.x*self.x +self.y*self.y 
        m2=other.x*other.x+other.y*other.y
        print("less than equal")
        return m1<=m2

In [77]:
p1=Point(3,2)
p2=Point(4,-1)

In [78]:
p1>p2

greater

False

In [79]:
p1>=p2

greate equal

False

In [80]:
p1<=p2

less than equal

True

In [81]:
p1<p2

less than

True

In [82]:
p1==p2

equal

False

In [83]:
from dataclasses import dataclass

In [84]:
@dataclass
class Person:
    name:str
    age:int=0
    def sayhello(self):
        print(self.name," says hello age is",self.age)

In [85]:
p1=Person("Raj",22)

In [86]:
p1.sayhello()

Raj  says hello age is 22

In [87]:
class Normal:
    counter=0 #static--shared by all instances
    def __init__(self,n1):
        self.n1=n1
        Normal.counter=Normal.counter+1

In [88]:
n1=Normal(10)

In [89]:
n2=Normal(20)

In [91]:
Normal.counter

2

In [92]:
from collections import namedtuple

In [93]:
Cordinate=namedtuple("Cordinate","x y")

In [94]:
c1=Cordinate(22,33)

In [95]:
c1.x

22

In [96]:
c1.y

33

In [97]:
def add(a:int,b:int)->int:#hinting
    return a+b

In [98]:
add(22,33)

55

In [99]:
add("Hllo","World")

'HlloWorld'

In [107]:
class Sample5:
    def __init__(self,n1):
        self.n1=n1
        self.__res=0#in python __ is the name
    def __privateDisplay(self):
        print("n1 in private",self.n1)
    def display(self):
        print("n1",self.n1)
        print("res",self.__res)

In [108]:
s5=Sample5(55)

In [109]:
s5.n1

55

In [110]:
s5.__res#private variable

AttributeError: 'Sample5' object has no attribute '__res'

In [111]:
s5.display()

n1 55
res 0

In [112]:
s5._Sample5__res#private can be accessed by using this way

0

In [114]:
s5._Sample5__privateDisplay()

n1 in private 55

In [115]:
from abc import ABC,abstractmethod

In [116]:
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass
    def display(self):
        print("Display from Shape")

In [117]:
class Circle(Shape):
    def __init__(self,r):
        self.r=r
    def area(self):
        return 3.14*self.r*self.r

In [118]:
class Square(Shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
    def area(self):
        return self.l*self.b

In [121]:
class Sample6:
    def __init__(self,a):
        self.a=a
    @staticmethod
    def convertToUpper(text):
        return text.upper()

In [122]:
Sample6.convertToUpper("Hello")

'HELLO'

In [123]:
p1=Point(22,33)

In [124]:
import pickle

In [126]:
with open("C://training//data//p1.ser","wb") as op:
    pickle.dump(p1,op)

In [127]:
with open("C://training//data//p1.ser","rb") as ip:
    p2=pickle.load(ip)
    print(p2)

x 22 y33

In [128]:
#threading
#process ----memory,CPU
#threads ---light weight process
#process --multiple threads

In [129]:
import threading
import time

In [130]:
def performTask1(name):
    print("Thread",name,"started")
    time.sleep(2)
    print("Thread",name,"is done")

In [131]:
t1=threading.Thread(target=performTask1,args=("first thread",))

In [132]:
t1.start()

Thread first thread started
Thread first thread is done

In [133]:
class MyThread1(threading.Thread):
    def  __init__(self,name):
        threading.Thread.__init__(self)
        self.name=name
    def run(self):
        print("started running")
        self.name=self.name.upper()
        print("end running",self.name)

In [134]:
t2=MyThread1("worker1")

In [135]:
t2.start()

started running
end running WORKER1

In [137]:
import threading
import requests
import json

In [151]:
def download(url):
    print("Start downloading",url)
    data=requests.get(url)
    with open("C://training//data//todosfromthreads.json","w") as op:
        json.dump(data.json(),op)

In [152]:
t2=threading.Thread(target=download,args=("https://jsonplaceholder.typicode.com/todos/",))

In [153]:
t2.start()

Start downloading https://jsonplaceholder.typicode.com/todos/

In [154]:
from concurrent.futures import ThreadPoolExecutor

In [160]:
import random
def download(url):
    print("Starting to download",url)
    data=requests.get(url)
    with open("C://training//data//"+str(random.randint(2,6))+".json","w") as op:
        json.dump(data.json(),op)
    return("Done downloading"+url)

In [161]:
with ThreadPoolExecutor(max_workers=3) as executor:
    f1=executor.submit(download,"https://jsonplaceholder.typicode.com/todos/")
    f2=executor.submit(download,"https://jsonplaceholder.typicode.com/comments/")
    f3=executor.submit(download,"https://jsonplaceholder.typicode.com/posts/")
    f4=executor.submit(download,"https://jsonplaceholder.typicode.com/users/")
    print(f1.result())
    print(f2.result())
    print(f3.result())
    print(f4.result())

Starting to download https://jsonplaceholder.typicode.com/todos/
Starting to download https://jsonplaceholder.typicode.com/comments/
Starting to download https://jsonplaceholder.typicode.com/posts/
Starting to download https://jsonplaceholder.typicode.com/users/
Done downloadinghttps://jsonplaceholder.typicode.com/todos/
Done downloadinghttps://jsonplaceholder.typicode.com/comments/
Done downloadinghttps://jsonplaceholder.typicode.com/posts/
Done downloadinghttps://jsonplaceholder.typicode.com/users/

In [162]:
import os

In [163]:
os.cpu_count()

8

In [177]:
count=0
lock=threading.Lock()
def inc():
    global count
    print("Trying to get lock",threading.current_thread().name)
    time.sleep(2)
    lock.acquire()
    print("Lock is acquired",threading.current_thread().name)
    try:
        count=count+1
    except Exception as e:
        print("Exception",e)
    finally:
        lock.release()
        print("Lock is released",threading.current_thread())

In [178]:
t1=threading.Thread(target=inc,name="thread1")
t2=threading.Thread(target=inc,name="thread2")
t3=threading.Thread(target=inc,name="thread3")
t1.start()
t2.start()
t3.start()

Trying to get lock thread1
Trying to get lock thread2
Trying to get lock thread3
Lock is acquired thread1
Lock is released <Thread(thread1, started 30564)>
Lock is acquired thread2
Lock is released <Thread(thread2, started 27088)>
Lock is acquired thread3
Lock is released <Thread(thread3, started 17916)>

In [176]:
count

3

In [179]:
import asyncio

In [180]:
async def welcome(delay,message):
    print("started",message)
    await asyncio.sleep(delay)
    print("Done",message)

In [181]:
async def performThreading():
    t1=asyncio.create_task(welcome(2,"Welcome 1"))
    t2=asyncio.create_task(welcome(2,"Welcome 2"))
    t3=asyncio.create_task(welcome(2,"Welcome 3"))
    await asyncio.gather(t1,t2,t3)

In [184]:
await (performThreading())

started Welcome 1
started Welcome 2
started Welcome 3
Done Welcome 1
Done Welcome 2
Done Welcome 3

In [186]:
pip install aiohttp

Collecting aiohttp
  Obtaining dependency information for aiohttp from https://files.pythonhosted.org/packages/c3/63/688462108c1a00eb9f05765331c107f95ae86f6b197b865d29e930b7e462/aiohttp-3.13.2-cp311-cp311-win_amd64.whl.metadata
  Downloading aiohttp-3.13.2-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp)
  Obtaining dependency information for aiohappyeyeballs>=2.5.0 from https://files.pythonhosted.org/packages/0f/15/5bf3b99495fb160b63f95972b81750f18f7f4e02ad051373b669d17d44f2/aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp)
  Obtaining dependency information for aiosignal>=1.4.0 from https://files.pythonhosted.org/packages/fb/76/641ae371508676492379f16e2fa48f4e2c11741bd63c48be4b12a6b09cba/aiosignal-1.4.0-py3-none-any.whl.metadata
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from aiohttp) (25.3.0)
Collecting frozenlist>=1.1.1 (from aiohttp)
  Obtaining dependency information for frozenlist>=1.1.1 from https://files.pythonhosted.org/packages/0a/f5/603d0d6a02cfd4c8f2a095a54672b3cf967ad688a60fb9faf04fc4887f65/frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp)
  Obtaining dependency information for multidict<7.0,>=4.5 from https://files.pythonhosted.org/packages/32/0f/13228f26f8b882c34da36efa776c3b7348455ec383bab4a66390e42963ae/multidict-6.7.0-cp311-cp311-win_amd64.whl.metadata
  Downloading multidict-6.7.0-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp)
  Obtaining dependency information for propcache>=0.2.0 from https://files.pythonhosted.org/packages/f4/78/6cce448e2098e9f3bfc91bb877f06aa24b6ccace872e39c53b2f707c4648/propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp)
  Obtaining dependency information for yarl<2.0,>=1.17.0 from https://files.pythonhosted.org/packages/b5/f7/149bb6f45f267cb5c074ac40c01c6b3ea6d8a620d34b337f6321928a1b4d/yarl-1.22.0-cp311-cp311-win_amd64.whl.metadata
  Downloading yarl-1.22.0-cp311-cp311-win_amd64.whl.metadata (77 kB)
     ---------------------------------------- 0.0/77.6 kB ? eta -:--:--
     ---------------------------------------- 77.6/77.6 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from aiosignal>=1.4.0->aiohttp) (4.13.2)
Requirement already satisfied: idna>=2.0 in c:\python311\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp) (3.10)
Downloading aiohttp-3.13.2-cp311-cp311-win_amd64.whl (456 kB)
   ---------------------------------------- 0.0/456.2 kB ? eta -:--:--
   ------------------------- -------------- 286.7/456.2 kB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 456.2/456.2 kB 7.2 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
   ---------------------------------------- 0.0/44.1 kB ? eta -:--:--
   ---------------------------------------- 44.1/44.1 kB 2.1 MB/s eta 0:00:00
Downloading multidict-6.7.0-cp311-cp311-win_amd64.whl (46 kB)
   ---------------------------------------- 0.0/46.0 kB ? eta -:--:--
   ---------------------------------------- 46.0/46.0 kB ? eta 0:00:00
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
   ---------------------------------------- 0.0/41.6 kB ? eta -:--:--
   ---------------------------------------- 41.6/41.6 kB ? eta 0:00:00
Downloading yarl-1.22.0-cp311-cp311-win_amd64.whl (86 kB)
   ---------------------------------------- 0.0/86.9 kB ? eta -:--:--
   ---------------------------------------- 86.9/86.9 kB 4.8 MB/s eta 0:00:00
Installing collected packages: propcache, multidict, frozenlist, aiohappyeyeballs, yarl, aiosignal, aiohttp
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.2 aiosignal-1.4.0 frozenlist-1.8.0 multidict-6.7.0 propcache-0.4.1 yarl-1.22.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [187]:
import aiohttp
import asyncio

In [188]:
async def download(session,url):
    async with session.get(url) as response:
        response.raise_for_status()
        return await response.text()

In [191]:
async def downloadeg():
    urls=["https://jsonplaceholder.typicode.com/todos/1",
          "https://jsonplaceholder.typicode.com/todos/2",
          "https://jsonplaceholder.typicode.com/todos/3"]
    async with aiohttp.ClientSession() as session:
        tasks=[download(session,url) for url in urls]
        results=await asyncio.gather(*tasks)
        for url,content in zip(urls,results):
            print("url",url)
            print(content)

In [192]:
await downloadeg()

url https://jsonplaceholder.typicode.com/todos/1
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
url https://jsonplaceholder.typicode.com/todos/2
{
  "userId": 1,
  "id": 2,
  "title": "quis ut nam facilis et officia qui",
  "completed": false
}
url https://jsonplaceholder.typicode.com/todos/3
{
  "userId": 1,
  "id": 3,
  "title": "fugiat veniam minus",
  "completed": false
}

In [193]:
import threading

In [194]:
semaphore=threading.Semaphore(2) #Allows configured no od threads to enter critical section
def task(name):
    with semaphore:
        print(name,"acquired")
        time.sleep(2)
        print(name,"release")

In [195]:
t1=threading.Thread(target=task,args=("first",))
t2=threading.Thread(target=task,args=("second",))
t3=threading.Thread(target=task,args=("third",))
t4=threading.Thread(target=task,args=("four",))
t1.start()
t2.start()
t3.start()
t4.start()

first acquired
second acquired
first release
second release
third acquired
four acquired
four release
third release

In [197]:
pip install schedule

Collecting schedule
  Obtaining dependency information for schedule from https://files.pythonhosted.org/packages/20/a7/84c96b61fd13205f2cafbe263cdb2745965974bdf3e0078f121dfeca5f02/schedule-1.2.2-py3-none-any.whl.metadata
  Downloading schedule-1.2.2-py3-none-any.whl.metadata (3.8 kB)
Downloading schedule-1.2.2-py3-none-any.whl (12 kB)
Installing collected packages: schedule
Successfully installed schedule-1.2.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [198]:
import schedule

In [200]:
def sayhello():
    print("hello")

In [201]:
schedule.every(3).seconds.do(sayhello)

Every 3 seconds do sayhello() (last run: [never], next run: 2025-11-13 15:16:22)

In [203]:
while True:
    schedule.run_pending()

hello
hello
hello
hello
hello

KeyboardInterrupt:

In [205]:
pip install apscheduler

Collecting apscheduler
  Obtaining dependency information for apscheduler from https://files.pythonhosted.org/packages/58/9f/d3c76f76c73fcc959d28e9def45b8b1cc3d7722660c5003b19c1022fd7f4/apscheduler-3.11.1-py3-none-any.whl.metadata
  Downloading apscheduler-3.11.1-py3-none-any.whl.metadata (6.4 kB)
Collecting tzlocal>=3.0 (from apscheduler)
  Obtaining dependency information for tzlocal>=3.0 from https://files.pythonhosted.org/packages/c2/14/e2a54fabd4f08cd7af1c07030603c3356b74da07f7cc056e600436edfa17/tzlocal-5.3.1-py3-none-any.whl.metadata
  Downloading tzlocal-5.3.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: tzdata in c:\python311\lib\site-packages (from tzlocal>=3.0->apscheduler) (2025.2)
Downloading apscheduler-3.11.1-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/64.3 kB ? eta -:--:--
   ------ --------------------------------- 10.2/64.3 kB ? eta -:--:--
   -------------------------------------- - 61.4/64.3 kB 825.8 kB/s eta 0:00:01
   ---------------------------------------- 64.3/64.3 kB 692.8 kB/s eta 0:00:00
Downloading tzlocal-5.3.1-py3-none-any.whl (18 kB)
Installing collected packages: tzlocal, apscheduler
Successfully installed apscheduler-3.11.1 tzlocal-5.3.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [206]:
from apscheduler.schedulers.background import BackgroundScheduler

In [207]:
scheduler=BackgroundScheduler()
scheduler.add_job(sayhello,"interval",seconds=5)
scheduler.start()

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

In [208]:
scheduler.shutdown()

In [209]:
help(scheduler.add_job)

Help on method add_job in module apscheduler.schedulers.base:

add_job(func, trigger=None, args=None, kwargs=None, id=None, name=None, misfire_grace_time=<undefined>, coalesce=<undefined>, max_instances=<undefined>, next_run_time=<undefined>, jobstore='default', executor='default', replace_existing=False, **trigger_args) method of apscheduler.schedulers.background.BackgroundScheduler instance
    add_job(func, trigger=None, args=None, kwargs=None, id=None,             name=None, misfire_grace_time=undefined, coalesce=undefined,             max_instances=undefined, next_run_time=undefined,             jobstore='default', executor='default',             replace_existing=False, **trigger_args)

    Adds the given job to the job list and wakes up the scheduler if it's already running.

    Any option that defaults to ``undefined`` will be replaced with the corresponding default
    value when the job is scheduled (which happens when the scheduler is started, or
    immediately if the scheduler is already running).

    The ``func`` argument can be given either as a callable object or a textual reference in
    the ``package.module:some.object`` format, where the first half (separated by ``:``) is an
    importable module and the second half is a reference to the callable object, relative to
    the module.

    The ``trigger`` argument can either be:
      #. the alias name of the trigger (e.g. ``date``, ``interval`` or ``cron``), in which case
        any extra keyword arguments to this method are passed on to the trigger's constructor
      #. an instance of a trigger class

    :param func: callable (or a textual reference to one) to run at the given time
    :param str|apscheduler.triggers.base.BaseTrigger trigger: trigger that determines when
        ``func`` is called
    :param list|tuple args: list of positional arguments to call func with
    :param dict kwargs: dict of keyword arguments to call func with
    :param str|unicode id: explicit identifier for the job (for modifying it later)
    :param str|unicode name: textual description of the job
    :param int misfire_grace_time: seconds after the designated runtime that the job is still
        allowed to be run (or ``None`` to allow the job to run no matter how late it is)
    :param bool coalesce: run once instead of many times if the scheduler determines that the
        job should be run more than once in succession
    :param int max_instances: maximum number of concurrently running instances allowed for this
        job
    :param datetime next_run_time: when to first run the job, regardless of the trigger (pass
        ``None`` to add the job as paused)
    :param str|unicode jobstore: alias of the job store to store the job in
    :param str|unicode executor: alias of the executor to run the job with
    :param bool replace_existing: ``True`` to replace an existing job with the same ``id``
        (but retain the number of runs from the existing one)
    :rtype: Job

In [210]:
url_link = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"
import pandas as pd

In [212]:
import requests
#the website URL
url_link = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"
result = requests.get(url_link,headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"}).text

In [213]:
from io import StringIO

In [215]:
tables=pd.read_html(StringIO(result))

In [216]:
tables[0]

                                                    0
0                 This article is part of a series on
1            Political divisions of the United States
2                                         First level
3   State (Commonwealth) Federal district Territor...
4                                        Second level
5   County / Parish / Borough Unorganized Borough ...
6                                         Third level
7   Township Cities, towns, and villages Cotermino...
8                                        Fourth level
9                                                Ward
10                                        Other areas
11  Protected areas (Conservation district, Nation...
12                               United States portal
13                                                vte

In [218]:
len(tables)

22

In [217]:
tables[1]

   Flag, name and postal abbreviation[8]  \
   Flag, name and postal abbreviation[8]
0                                Alabama
1                                 Alaska
2                                Arizona
3                               Arkansas
4                             California
5                               Colorado
6                            Connecticut
7                               Delaware
8                                Florida
9                                Georgia
10                                Hawaii
11                                 Idaho
12                              Illinois
13                               Indiana
14                                  Iowa
15                                Kansas
16                           Kentucky[B]
17                             Louisiana
18                                 Maine
19                              Maryland
20                      Massachusetts[B]
21                              Michigan
22                             Minnesota
23                           Mississippi
24                              Missouri
25                               Montana
26                              Nebraska
27                                Nevada
28                         New Hampshire
29                            New Jersey
30                            New Mexico
31                              New York
32                        North Carolina
33                          North Dakota
34                                  Ohio
35                              Oklahoma
36                                Oregon
37                       Pennsylvania[B]
38                          Rhode Island
39                        South Carolina
40                          South Dakota
41                             Tennessee
42                                 Texas
43                                  Utah
44                               Vermont
45                           Virginia[B]
46                            Washington
47                         West Virginia
48                             Wisconsin
49                               Wyoming

                                                    Cities                  \
   Flag, name and postal abbreviation[8].1         Capital     Largest[12]
0                                       AL      Montgomery      Huntsville
1                                       AK          Juneau       Anchorage
2                                       AZ         Phoenix         Phoenix
3                                       AR     Little Rock     Little Rock
4                                       CA      Sacramento     Los Angeles
5                                       CO          Denver          Denver
6                                       CT        Hartford      Bridgeport
7                                       DE           Dover      Wilmington
8                                       FL     Tallahassee    Jacksonville
9                                       GA         Atlanta         Atlanta
10                                      HI        Honolulu        Honolulu
11                                      ID           Boise           Boise
12                                      IL     Springfield         Chicago
13                                      IN    Indianapolis    Indianapolis
14                                      IA      Des Moines      Des Moines
15                                      KS          Topeka         Wichita
16                                      KY       Frankfort      Louisville
17                                      LA     Baton Rouge     New Orleans
18                                      ME         Augusta        Portland
19                                      MD       Annapolis       Baltimore
20                                      MA          Boston          Boston
21                                      MI         Lansing         Detroit
22                                      MN      Saint Paul     Minneapolis
23                                      MS         Jackson         Jackson
24                                      MO  Jefferson City     Kansas City
25                                      MT          Helena        Billings
26                                      NE         Lincoln           Omaha
27                                      NV     Carson City       Las Vegas
28                                      NH         Concord      Manchester
29                                      NJ         Trenton          Newark
30                                      NM        Santa Fe     Albuquerque
31                                      NY          Albany   New York City
32                                      NC         Raleigh       Charlotte
33                                      ND        Bismarck           Fargo
34                                      OH        Columbus        Columbus
35                                      OK   Oklahoma City   Oklahoma City
36                                      OR           Salem        Portland
37                                      PA      Harrisburg    Philadelphia
38                                      RI      Providence      Providence
39                                      SC        Columbia      Charleston
40                                      SD          Pierre     Sioux Falls
41                                      TN       Nashville       Nashville
42                                      TX          Austin         Houston
43                                      UT  Salt Lake City  Salt Lake City
44                                      VT      Montpelier      Burlington
45                                      VA        Richmond  Virginia Beach
46                                      WA         Olympia         Seattle
47                                      WV      Charleston      Charleston
48                                      WI         Madison       Milwaukee
49                                      WY        Cheyenne        Cheyenne

   Ratification or admission[A] Population (2020)[10] Total area[11]           \
   Ratification or admission[A] Population (2020)[10]            mi2      km2
0                  Dec 14, 1819               5024279          52420   135767
1                   Jan 3, 1959                733391         665384  1723337
2                  Feb 14, 1912               7151502         113990   295234
3                  Jun 15, 1836               3011524          53179   137732
4                   Sep 9, 1850              39538223         163695   423967
5                   Aug 1, 1876               5773714         104094   269601
6                   Jan 9, 1788               3605944           5543    14357
7                   Dec 7, 1787                989948           2489     6446
8                   Mar 3, 1845              21538187          65758   170312
9                   Jan 2, 1788              10711908          59425   153910
10                 Aug 21, 1959               1455271          10932    28313
11                  Jul 3, 1890               1839106          83569   216443
12                  Dec 3, 1818              12812508          57914   149995
13                 Dec 11, 1816               6785528          36420    94326
14                 Dec 28, 1846               3190369          56273   145746
15                 Jan 29, 1861               2937880          82278   213100
16                  Jun 1, 1792               4505836          40408   104656
17                 Apr 30, 1812               4657757          52378   135659
18                 Mar 15, 1820               1362359          35380    91633
19                 Apr 28, 1788               6177224          12406    32131
20                  Feb 6, 1788               7029917          10554    27336
21                 Jan 26, 1837              10077331          96714   250487
22                 May 11, 1858               5706494          86936   225163
23                 Dec 10, 1817               2961279          48432   125438
24                 Aug 10, 1821               6154913          69707   180540
25                  Nov 8, 1889               1084225         147040   380831
26                  Mar 1, 1867               1961504          77348   200330
27                 Oct 31, 1864               3104614         110572   286380
28                 Jun 21, 1788               1377529           9349    24214
29                 Dec 18, 1787               9288994           8723    22591
30                  Jan 6, 1912               2117522         121590   314917
31                 Jul 26, 1788              20201249          54555   141297
32                 Nov 21, 1789              10439388          53819   139391
33                  Nov 2, 1889                779094          70698   183108
34                  Mar 1, 1803              11799448          44826   116098
35                 Nov 16, 1907               3959353          69899   181037
36                 Feb 14, 1859               4237256          98379   254799
37                 Dec 12, 1787              13002700          46054   119280
38                 May 29, 1790               1097379           1545     4001
39                 May 23, 1788               5118425          32020    82933
40                  Nov 2, 1889                886667          77116   199729
41                  Jun 1, 1796               6910840          42144   109153
42                 Dec 29, 1845              29145505         268596   695662
43                  Jan 4, 1896               3271616          84897   219882
44                  Mar 4, 1791                643077           9616    24906
45                 Jun 25, 1788               8631393          42775   110787
46                 Nov 11, 1889               7705281          71298   184661
47                 Jun 20, 1863               1793716          24230    62756
48                 May 29, 1848               5893718          65496   169635
49                 Jul 10, 1890                576851          97813   253335

   Reps.
   Reps.
0      7
1      1
2      9
3      4
4     52
5      8
6      5
7      1
8     28
9     14
10     2
11     2
12    17
13     9
14     4
15     4
16     6
17     6
18     2
19     8
20     9
21    13
22     8
23     4
24     8
25     2
26     3
27     4
28     2
29    12
30     3
31    26
32    14
33     1
34    15
35     5
36     6
37    17
38     2
39     7
40     1
41     9
42    38
43     4
44     1
45    11
46    10
47     2
48     8
49     1

In [238]:
location={27:1,21:9,17:4,19:8,3:22,11:26,20:29,5:8}

In [239]:
import random

In [240]:
def throwDice():
    return random.randint(1,6)

In [228]:
score  = 0
while score != 30:
    diceValue=throwDice()
    if score+diceValue > 30:
        continue
    else:
        score=score+diceValue
        if score in location:
            if location[score]> score:
                print("Ladder")
            else:
                print("snake")
            score=location[score]
        print(score)

Ladder
8
14
snake
8
14
snake
4
6
7
10
Ladder
26
29
30

In [241]:
def roll(playerkey,score):
    diceValue=throwDice()
    if score+diceValue > 30:
        print("non feasible")
    else:
        score=score+diceValue
        if score in location:
            if location[score]> score:
                print("Ladder")
                return location[score]
            else:
                print("snake")
                score=location[score]
    return(score)

In [243]:
players={}
players["1"]=0
players["2"]=0
condition=1
while condition==1:
    for k,v in players.items():
        print(k,"rolling dice",v)
        score=roll(k,v)
        print(score)
        players[k]=score
        if players[k]==30:
            print(k,"won")
            condition=0
            break

1 rolling dice 0
6
2 rolling dice 0
Ladder
22
1 rolling dice 6
Ladder
26
2 rolling dice 22
28
1 rolling dice 26
29
2 rolling dice 28
non feasible
28
1 rolling dice 29
30
1 won

In [247]:
def playsnakeandladder(noofplayers):
    players={}
    for i in range(1,noofplayers+1):
        players[str(i)]=0

    condition=1
    while condition==1:
        for k,v in players.items():
            print(k,"rolling dice",v)
            score=roll(k,v)
            print(score)
            players[k]=score
            if players[k]==30:
                print(k,"won")
                condition=0
                break

In [248]:
playsnakeandladder(3)

1 rolling dice 0
4
2 rolling dice 0
1
3 rolling dice 0
Ladder
8
1 rolling dice 4
6
2 rolling dice 1
2
3 rolling dice 8
10
1 rolling dice 6
7
2 rolling dice 2
7
3 rolling dice 10
14
1 rolling dice 7
13
2 rolling dice 7
Ladder
26
3 rolling dice 14
snake
8
1 rolling dice 13
14
2 rolling dice 26
snake
1
3 rolling dice 8
10
1 rolling dice 14
16
2 rolling dice 1
Ladder
22
3 rolling dice 10
12
1 rolling dice 16
snake
9
2 rolling dice 22
26
3 rolling dice 12
16
1 rolling dice 9
15
2 rolling dice 26
snake
1
3 rolling dice 16
18
1 rolling dice 15
snake
9
2 rolling dice 1
6
3 rolling dice 18
snake
8
1 rolling dice 9
14
2 rolling dice 6
8
3 rolling dice 8
Ladder
26
1 rolling dice 14
snake
4
2 rolling dice 8
9
3 rolling dice 26
30
3 won